### ISSUE TITLE
fix: Wrong position of thumb in FluentSlider after attempt to move thumb

### ISSUE THREAD

**Issue by vadzimshch** [microsoft/fluentui-blazor#1011]
# 🐛 Bug Report
I tried to use EditForm with several FluentSliders inside dialog. 
## 💻 Repro or Code Sample
[ThumbBugTestProject.zip](https://github.com/microsoft/fluentui-blazor/files/13448423/ThumbBugTestProject.zip)

1. Click button "Open dialog" on Home page
2. Try to move thumb of any slider inside dialog

## 🤔 Expected Behavior

Thumb must stay on the same horizontal line

## 😯 Current Behavior

Thumbs jumps to new position outside his slider

**Comment by vnbaaij** [comment]
The sliders underlying web component adds a value for the orientation (horizontal/vertical to the class attribute. The functionality that adds the valid/invalid/modified  (through the `EditContext`) value to the class attribute does not know the orientation is in there as well (it is added with the web componets javascript) so it gets removed when the `EditForm`\`EditContext` do their work. 

The fix is to add a `Class="horizontal"` parameter to the sliders and then it all works with the `EditForm` as it should. We will look at providing a fix out-of-the box for a next release.

Thanks for providing the sample code. Made finding this a lot easier.
