### ISSUE TITLE
fix: auto active other item after tab item closed in FluentTabs .

### ISSUE THREAD

**Issue by a44281071** [microsoft/fluentui-blazor#1029]
# 🐛 Bug Report

The close operation causes the first tab item to be selected by default.

## 💻 Repro or Code Sample

see tabs Dynamic demo: https://www.fluentui-blazor.net/Tabs

## 🤔 Expected Behavior

scene 1:
- In Dynamic demo, I select item month 5, selected index is 4.
- Click close button, remove item month 5.
- Current active item is month 6 (selected index is 4).
- Auto select adjacent item.

scene 2:
- In Dynamic demo, I select item month 5, selected index is 4.
- Click close button in month 4, remove item month 4.
- Current active item is month 5 (selected index is 3).
- Keep select same item.

## 😯 Current Behavior

**Comment by dvoituron** [comment]
Hello,
Thank you for your comment. This could be another possibility, but at the moment we've chosen to go back to the first element. When a tab is removed from the list, we of course have to go back to an existing element. What's wrong with going back to the first element instead of an adjacent one?
