### ISSUE TITLE
docs: fix/add documention on how to set up the Toast Service

### ISSUE THREAD

**Issue by gsnyder87** [microsoft/fluentui-blazor#1060]
# 🙋 Documentation Request

I think that there must be some documentation missing on how to get the Toast Service working. 
I created a new project from the Fluent Blazor Web App Project. 
on the mainLayout page I added the FluentToastProvidor

```csharp
<FluentStack Class="main" Orientation="Orientation.Horizontal" Width="100%">
        <NavMenu />
        <FluentBodyContent>
            <div class="content">
                @Body
            </div>
            <FluentToastProvider></FluentToastProvider>
        </FluentBodyContent>
    </FluentStack>
```

on the template Counter.razor page, I injected the service, and added the example button and ShowToast() method.

```csharp
@page "/counter"
@rendermode InteractiveServer
@inject IToastService ToastService

<PageTitle>Counter</PageTitle>

<FluentButton @onclick="@ShowToast" Appearance="Appearance.Accent">Open</FluentButton>

<h1>Counter</h1>

<p role="status">Current count: <FluentBadge Appearance="Appearance.Neutral">@currentCount</FluentBadge></p>

<FluentButton Appearance="Appearance.Accent" @onclick="IncrementCount">Click me</FluentButton>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }

    int counter = 1;
    void ShowToast()
    {
        Random rnd = new();

        var intent = Enum.GetValues<ToastIntent>()[rnd.Next(10)];
        var message = $"Simple Toast #{counter++}";
        ToastService.ShowToast(intent, message);
    }
}
```

Also, the provider example is still referencing the old FluentToastContainer in the example instead of the Provider. component
https://www.fluentui-blazor.net/Toast

**Comment by vnbaaij** [comment]
Hi.,

Judging from the `@rendermode InteractiveServer` code in the Counter page, you choose to create the site with `per page` interactivity. This means the `MainLayout` will use the (default) SSR mode and because of that the `FluentToastProvider` does not exist when the Counter page is being rendered/executed. Does that make sense? To fix, the MainLayout needs to be interactive too.
We'll add some more details to the docs on this (and update the Container references, thanks for reporting!)

**Comment by gsnyder87** [comment]
for anyone viewing this, if you add a render mode declaration on the component, then it fixes it.

```csharp
<FluentToastProvider @rendermode=RenderMode.InteractiveServer MaxToastCount="10" />
```

**Comment by alexdrenea** [comment]
Maybe I'm missing something, but if you do add `<FluentToastProvider @rendermode=RenderMode.InteractiveServer MaxToastCount="10" />` in your MainLayout doesn't that cause every page to require a websocket opened in order to support that?

My goal is to have most of my pages be SSR - and I want no WS connection to my server. Only when you navigate to an interactive page do I want the websocket... Does that make sense? Is there a way to achieve this by adding the `<FluentToastProvider\>` directly in my page? Or is my concern not really valid ?

**Comment by vnbaaij** [comment]
Yes, you will have a ws connection.

Don't you think it is obvious that having a Toast component requires interactivity? Where is the toast (and the content it shows) coming from? Not from static html that is on the client already.
