### ISSUE TITLE
docs: fix/add [what] to/in https://www.fluentui-blazor.net/icon

### ISSUE THREAD

**Issue by Spinachy** [microsoft/fluentui-blazor#1061]
# 🙋 Documentation Request

On this page (https://www.fluentui-blazor.net/icon), I should be able to "copy" the component declaration to my clipboard - 
"Click on upper right clipboard icon in a card to copy a ready to paste FluentIcon component declaration to the clipboard"

But clicking on the clipboard Icon on the top right of any card does not copy anything to my clipboard .....

## 💁 Possible Solution
Looks like a regression - this used to work ?

**Comment by dvoituron** [comment]
In fact, we've integrated the icon and emoji explorer into an IFrame to improve overall website performance. To avoid loading these thousands of assets locally in the user's browser, since we publish the documentation in WASM mode.
And it seems that this "Copy to clipboard" functionality is being blocked by this IFrame.
Let's see how to fix it.

In the meantime, you can double-click on the icon name to copy its name and add it to the following code.
(replacing `Info` with your icon name)

```xml
<FluentIcon Value="@(new Icons.Regular.Size24.Info())" />
```
