### ISSUE TITLE
Blazor FluentDataGrid Does Not Display Properly When RowStyle Sets Background-Color

### ISSUE THREAD

**Issue by marqdouj-spartan** [microsoft/fluentui-blazor#1198]
# 🐛 Bug Report

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by marqdouj-spartan** [comment]
hit the enter key so it posed without content.

I originally filed this as VS bug here:
https://developercommunity.visualstudio.com/t/Blazor-FluentDataGrid-Does-Not-Display-P/10543868

Microsoft.FluentUI.AspNetCore.Components Version 4.2.0
https://www.fluentui-blazor.net/DataGrid

`
@using Microsoft.FluentUI.AspNetCore.Components

<FluentDataGrid Items="@people" GenerateHeader="GenerateHeaderOption.Sticky" ResizableColumns=true OnRowFocus="@OnRowFocus" RowClass="@rowClass" RowStyle="@rowStyle" TGridItem="Person">
    <PropertyColumn Property="@(p => p.PersonId)" Sortable="true"/>
    <PropertyColumn Property="@(p => p.Name)" Sortable="true" />
    <PropertyColumn Property="@(p => p.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
</FluentDataGrid>

@code {
    IQueryable<Person> people = new[]
    {
        new Person(10895, "Jean Martin", new DateOnly(1985, 3, 16)),
        new Person(10944, "António Langa", new DateOnly(1991, 12, 1)),
        new Person(11203, "Julie Smith", new DateOnly(1958, 10, 10)),
        new Person(11205, "Nur Sari", new DateOnly(1922, 4, 27)),
        new Person(11898, "Jose Hernandez", new DateOnly(2011, 5, 3)),
        new Person(12130, "Kenji Sato", new DateOnly(2004, 1, 9)),
    }. AsQueryable();

Func<Person, string> rowClass = x => x.FocusedRow ? "highlighted-row" : null;
    Func<Person, string> rowStyle = x => x.FocusedRow ? "background-color: var(--highlight-bg);" : null;

private void OnRowFocus(FluentDataGridRow<Person> row)
    {
        var activeP = (Person)row. Item;

foreach (var p in people)
            p.FocusedRow = ReferenceEquals(p, activeP);

Console.WriteLine($"Row Focused: {row. RowIndex} - {activeP?. Name}");
    }

record Person(int PersonId, string Name, DateOnly BirthDate)
    {
        public bool FocusedRow { get; set; }
    }
}
`
When then page loads the columns/data is aligned properly:
![B14c2ab2334c24d82a420c6d7d54b75b7638385178675679214_20231218-103746-image](https://github.com/microsoft/fluentui-blazor/assets/97969185/5522191c-dd57-4168-a2be-5980f4acd671)

When I click on a row the data no longer appears under the column header:

![B1911d1a93c4e4f41871b446b972af224638385179286837869_20231218-103848-image](https://github.com/microsoft/fluentui-blazor/assets/97969185/b7bb2c79-ebc2-4c3b-a174-27d6c8731447)


If I select different rows then each rows is displayed out of alignment:

![B159d0e2add7841b0a92e3b09661f1a9a638385180472876619_20231218-104047-image](https://github.com/microsoft/fluentui-blazor/assets/97969185/76b2b0e6-2f85-43d5-b5bf-418d8caf2bad)

**Comment by marqdouj-spartan** [comment]
I won't let me post the code for using the data grid. Please see link above for the complete example.

**Comment by vnbaaij** [comment]
Hi,

I got your sample code running and can see the issue. Unfortunately, I can't fix it in a good way with the `RowStyle` being used this way.
The reason is that the underlying web component script uses the style attribute as well. It puts the value for `grid-template-columns` in there. When the `RowStyle` is being applied, that `grid-template-columns` value gets removed and that is why you see the misaligned output. I found a way to re-add the `grid-template-columns value` but  that is not a fool-proof solution. 

When you resize a column, the `grid-column-template` value is re-written through script as well and it would get very complicated to sync that to the Blazor side (so it could get re-applied when a row is being re-rendered once highlighted.

However, if you add the following:
```
<style>
    .highlighted-row {
        background-color: var(--highlight-bg);
    }
</style>
```
at the top of your code and just remove the `RowStyle` parameter (and the `rowStyle` assignment). Highlighting works exactely how you would expect it to work by means of the `RowClass` being applied to the highlighted row.

So botomline, `RowStyle` should not be used in an interactive way. It can be used to style an initial grid situation, but can not be used dynamically  as that interferes with column size (and re-sizing). I'll add a note to the docs about this.

Closing this as a workaround is available by using `RowClass`

**Comment by marqdouj-spartan** [comment]
I forgot to mention here (which I did in my VS post) that I couldn't get RowClass to work so that is why I tried RowStyle.
I must be missing something then with RowClass - I'll try again.

Thanks.

**Comment by vnbaaij** [comment]
Only thing I added to make it work was the `<style>` block

**Comment by marqdouj-spartan** [comment]
Ok, got to work now - thanks!

However, now I have to figure out how to change the highlight color to match the theme/color (I'm using FluentDesignTheme component)

I can't see the text in many of the colors:

![image](https://github.com/microsoft/fluentui-blazor/assets/97969185/ca2ab523-c336-41f5-b8f5-fe8be547201f)

**Comment by vnbaaij** [comment]
Using these styles 
```css
<style>
    .highlighted-row {
        background-color: var(--accent-fill-rest);
    }
    .highlighted-row > fluent-data-grid-cell {
        color: var(--foreground-on-accent-rest);
    }
</style>
```
gives me:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/6c0b4ddc-5d32-4a4a-ba7e-6b2f48757db0)
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/f86764cc-6906-47dc-8f00-a237ad659df9)

**Comment by marqdouj-spartan** [comment]
Works - thanks!
