### ISSUE TITLE
FluentButton does not allow to set preventDefault for onclick event

### ISSUE THREAD

**Issue by MisterGoodcat** [microsoft/fluentui-blazor#1202]
# 🐛 Bug Report

How can options like `preventDefault` can be set for the `onclick` event on `FluentButton`?

## 💻 Repro or Code Sample

`<button type="button" @onclick="() => {}" @onclick:preventDefault>Click</button>`

This works as expected.

`<FluentButton Type="ButtonType.Button" @onclick="() => {}" @onclick:preventDefault>Click</FluentButton>` 

Results in "error RZ10010: The component parameter 'onclick' is used two or more times for this component."

## 🤔 Expected Behavior

It should be possible to set these options.

**Comment by vnbaaij** [comment]
The `@onclick:stopPropagation` and `preventDefault` directives only work on HTML DOM elements. See also https://learn.microsoft.com/en-us/aspnet/core/blazor/components/event-handling?view=aspnetcore-8.0#stop-event-propagation

If you would try this on a standard Blazor component, you will get the same error:
`<InputText @bind-Value="@YYY" @oninput="XXX" @oninput:stopPropagation=true />`
gives
`RZ10010	The component parameter 'oninput' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'oninput' is generated by the '@oninput:stopPropagation' directive attribute.`

**Comment by Valkozaur** [comment]
But is there a workaround that? 
@vnbaaij

**Comment by Valkozaur** [comment]
Hello @vnbaaij 
I am trying to build a tree which Add Tree Node button in it. 
This is my code that is currently working:
```
<FluentTreeView>
    @foreach (var group in _groups)
    {
        <FluentTreeItem>
            <FluentIcon Icon="Icons.Regular.Size20.Folder" Slot="start" Data="group"/>
            @group.Name
            @foreach (var item in group.items)
            {
                <FluentTreeItem Data="item" AdditionalAttributes="@(new Dictionary<string, object>() { {"parent", group} })">
                    <FluentIcon Value="@(new Icons.Regular.Size20.Check())" />
                    @item.Name
                    <FluentIcon Value="new Icons.Regular.Size20.Delete()" OnClick="() => OnDeleteitem(group, item)" />
                </FluentTreeItem>
            }
            </FluentTreeItem>
        </FluentTreeItem>
    }

    //Add item node button
    <FluentTreeItem @onclick="() => _isAddingGroup = true"> //Change the state to adding if the fluent tree item is clicked
        @if (_isAddingGroup) // If the state is adding, show the input field and buttons
        {
            <FluentTextField Placeholder="item group name" Value="@_newGroupName" ValueChanged="(newValue) => _newGroupName = newValue" Style="width:100%;" /> // Input field for the group name
            <button @onclick="AddGroup" // In the add group button I set the state of _isAddingGroup to false.
                    @onclick:stopPropagation="true">    // Stop the event from propagating to the parent node otherwise the state will be changed to adding
                <FluentIcon Icon="Icons.Regular.Size20.Add" />
            </button>
            <button @onclick="(args) => _isAddingGroup = false"
                    @onclick:stopPropagation="true">
                <FluentIcon Icon="Icons.Regular.Size20.Delete" />
            </button>
        }
        else // Else show the add group button
        {
            <FluentIcon Icon="Icons.Regular.Size20.Add" />
            @("Add group")
        }
    </FluentTreeItem>
</FluentTreeView>
```

1. I create a node with an Icon and text "+ Add group"
2. I save state, if the node is clicked I set the state "_isAdding = true"
3. Than I show the input field + Add or Dismiss button.
4. When one of the buttons is added I set the state to "_isAdding = false" than I display back the "+ Add group" button.
5. I need to stop the propogation otherwise the OnClick event on the tree is always triggerd and the state is always set to ""isAdding = true" 

With the FluentButtons I can't stop the propagation. 

Two questions here:
1. Do you have any better idea how to implement this (I am trying to skip the RenderFragment option).
2. If there is no better idea how can I set the CSS of the given buttons to match the FluentButton css? 

Thanks for the help in advance.
