### ISSUE TITLE
fix: template FluentDataGrid is broken

### ISSUE THREAD

**Issue by kedare** [microsoft/fluentui-blazor#1347]
# 🐛 Bug Report

When creating a blank app using the Blazor Fluent template with `dotnet new fluentblazor`

The FluentDataGrid is missing all interactive features, it does shows up, but features like filtering and sorting are not working. 

This can be tested directly on `/weather` example page (or in any page you added that would be using the grid)

## 💻 Repro or Code Sample

- Create a default app with `dotnet new fluentblazor` using `Microsoft.FluentUI.AspNetCore.Templates 4.3.1`

- Start the project with `dotnet run`

- Go to the `/weather` page

- Try to use the sorting features, or try to resize the columns after having enabled resizing with `ResizableColumns=true`

## 🤔 Expected Behavior

Sorting and resizing should work fine

## 😯 Current Behavior

No feedbacks when trying to resize or sort

## 💁 Possible Solution

Likely something hasn't been imported properly in the template ?

## 🌍 Your Environment

* OS & Device: MaCOs
* Browser : Microsoft Edge
* .NET and FAST Version: .NET 8.0

**Comment by vnbaaij** [comment]
Hi,

When creating a project from the template with the settings you used, the pages will use SSR **by default** (the same as with the standard Web App template).

All things you are describing need interactivity to be enabled so a rendermode needs to be set on the component or page or app.

**Comment by vnbaaij** [comment]
Adding an extra remark to the Templates page in the site:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/17d8294a-225e-4a92-ae61-6bdb12ffb11f)

**Comment by kedare** [comment]
But then shouldn't be the template fixed by setting a rendermode in the Data Table ?
As the columns are set to be sortable (and have the appartenance of sortable columns) in the code but it doesn't work because the rendermode is missing.

It doesn't give a very good first impression as if even the official tenplate is not fully functional. (I switched to antblazor to continue my testing for example that had their data grid fully functional by default)

**Comment by vnbaaij** [comment]
> But then shouldn't be the template fixed by setting a rendermode in the Data Table ? As the columns are set to be sortable (and have the appartenance of sortable columns) in the code but it doesn't work because the rendermode is missing.

The output of the template is like this because of the choices that were made when the project was created. By defautl that will give you SSR with the Weather page grid as it is right now. If you make other choices when creating the project, the rendermode **will** get added to that page. I will look at the option of disabling sorting on that page in the default SSR mode.


> It doesn't give a very good first impression as if even the official tenplate is not fully functional. (I switched to antblazor to continue my testing for example that had their data grid fully functional by default)
Mostly agree. As sid will look at disabling sorting. 
As .NET 8 and SSR are still fairly new, I understand that the way it functions out of the box with SSR is not super clear for everyone, hence the extra remark in the readme and the page. I think (hope) it will make more sense once .NET 8 and SSR knowledge gets more wide spread. 
I don't know Antblazor well enough to know if the are supporting .NET 8 and SRR already. Props to them if they have a fully supported grid in that mode.

**Comment by vnbaaij** [comment]
> I will look at the option of disabling sorting on that page in the default SSR mode.

Ok, fixed that. Will be in v4.3.2 templates
