### ISSUE TITLE
fix: margin in Loading FluentButton without ChildContent

### ISSUE THREAD

**Issue by majkada** [microsoft/fluentui-blazor#1359]
# 🐛 Bug Report

I have a FluentButton with only an EndIcon without a ChildContent. When I set Loading to true the icon changes to a loading animation but there is an additional margin, which should only be shown when there is a ChildContent.

## 💻 Repro or Code Sample

`<FluentButton IconEnd="@(new Icons.Regular.Size16.Edit())" />`
`<FluentButton IconEnd="@(new Icons.Regular.Size16.Edit())" Loading />`

## 🤔 Expected Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/146962575/45708cd0-d8ad-4c58-aaf5-cd6240ff91a4)

## 😯 Current Behavior

![image](https://github.com/microsoft/fluentui-blazor/assets/146962575/c1768e83-4b37-4e9b-9925-d1286ca818ce)

## 💁 Possible Solution

Only add "end" css class if ChildContent is not null.

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge

**Comment by vnbaaij** [comment]
You get the desired effect by using the following "trick"

```
<FluentButton Appearance="Appearance.Accent"
              Loading="@loading"
              OnClick="@StartLoadingAsync" >
    <FluentIcon Value="@(new Icons.Regular.Size16.ArrowClockwise())" Color="@Color.Fill" />
</FluentButton>
```

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/70fa4c64-1ed5-421d-98aa-760f08fff575)

So, do not use a slot and use the icon as button "content"

I say trick, because the underlying web component does something with addin an extra class ('icon-only') when there is no content in the button. But we actually use content for displaying the progress ring and thefore the web component removes the class.
