### ISSUE TITLE
@code-block inside FluentDataGrid gets called three times instead of once

### ISSUE THREAD

**Issue by deadlimit** [microsoft/fluentui-blazor#1421]
# 🐛 Bug Report

I noticed that when I have a code block inside the FluentDataGrid-component the code gets called three times instead of just once? 

## 💻 Repro or Code Sample
```C#
@page "/"
@rendermode @(new InteractiveServerRenderMode(prerender: false))

<PageTitle>Home</PageTitle>

<h1>Hello, world!</h1>

<FluentDataGrid TGridItem="string">
    @{
        Console.WriteLine("Why is this called thrice?");
    }
</FluentDataGrid>
```
```
Output:
Why is this called thrice?
Why is this called thrice?
Why is this called thrice?
```

## 🤔 Expected Behavior

Should only be called once.

## 🌍 Your Environment

Code sample is from a new project, created from the Blazor Web App-template in VS2022. 

* OS & Device: Windows 10 PC
* Browser Google Chrome
* .NET and FAST Version .NET 8
* Microsoft.FluentUI.AspNetCore.Components v4.3.1

**Comment by vnbaaij** [comment]
Reverting this fix as it lead to other issues.
Code has been optimized a bit so now it is rendered twice. This has to do with the way the internals of the QuickGrid work. Have not found a way to circumvent it.

**Comment by vnbaaij** [comment]
Optimization lead to errors. We are back at three renders. But the good news is that this is actually be design and not an issue at all. Your expected behavior was not correct. 
I discussed this with Steve Sanderson (creator of QuickGrid which our grid is based on) and he explaind it as follows:

> In general, since QuickGrid is using ChildContent as a way of collecting the list of columns, the assumption is it's free to render that as often as it wants. In order to discover when columns are added/removed, it has to be able to invoke ChildContent on each render. 

You can see an exmple of how we are using that in the following code:
```
@inject DataSource Data

<p>
    Show:
    <FluentCheckbox @bind-Value="showName">Name</FluentCheckbox>
    <FluentCheckbox @bind-Value="showBirthDate">Birth date</FluentCheckbox>
</p>


    <FluentDataGrid Items="@Data.People" GridTemplateColumns="0.5fr 1fr 1fr" style="width: 500px;">
        <PropertyColumn Title="ID" Property="@(c => c.PersonId)" Sortable="true" />
        @if (showName)
        {
            <TemplateColumn Title="Name">
                <strong>@context.LastName</strong>, @context.FirstName
            </TemplateColumn>
        }
        @if (showBirthDate)
        {
            <PropertyColumn Title="Birth date" Property="@(c => c.BirthDate)" Format="yyyy-MM-dd" Sortable="true" />
        }
    </FluentDataGrid>


@code {
    bool showName = true;
    bool showBirthDate = false;
}
```
With a standard QuickGrid, your code would result in the output being shown twice. With Fluent version we get an extra one to cater for situations where the rows and cells are being supplied manually.

So, behavior is expected and should not lead to any issues in the output shown on screen.
