### ISSUE TITLE
FluentAppBarItem adds font size adjustment.

### ISSUE THREAD

**Issue by SoftGod4MrLi** [microsoft/fluentui-blazor#1766]
# 🙋 Feature Request

FluentAppBarItem adds font size adjustment.

## 🤔 Expected Behavior

I hope FluentAppBarItem can set the font size to be the same as FluentNavLink's font. As shown in the following figure:
![DF](https://github.com/microsoft/fluentui-blazor/assets/89335285/fee7c793-b776-436d-84f2-02b5bec39f0f)

## 😯 Current Behavior

The current font of FluentAppBarItem is too small, different from the font of FluentNavLink, and the display is not coordinated.

**Comment by vnbaaij** [comment]
This is by design. It is the same as in Teams where that text is smaller too. We will not be adding specific functionality to change that. 

If you really want/need to change it, the FluentAppBar has the Class and Style parameters you can use to make changes. You would need to target the a[part='listitem'] element to achieve your goal. (Probably needs '!important')

**Comment by SoftGod4MrLi** [comment]
Oh，I get it，thanks!

Just use CSS below:
.fluent-appbar-item a[role="listitem"] {
    font-size: 12px;
}
