### ISSUE TITLE
8 Seconds delay before interactivity kicks in using default Fluent template

### ISSUE THREAD

**Issue by michelmoorlag** [microsoft/fluentui-blazor#1796]
# 🐛 Bug Report

8 Seconds delay before interactivity kicks in using default template

## 💻 Repro or Code Sample

I installed the default templates with "dotnet new install Microsoft.FluentUI.AspNetCore.Templates". Then I created a new project and chose the "Fluent Blazor Web App" with .Net8.0, no authentication, configure for https set to true, Auto render mode per page/component including sample pages.

## 🤔 Expected Behavior

I would expect that after the application has started I can directly start navigating the nav menu

## 😯 Current Behavior

I can click the menu buttons for like 8 to 9 seconds but nothing happens. After this time everthing works as expected.
When I use the default Blazor Web app template with the same settings there is no delay. The menu works direct after loading.
One other interesting fact is that when I use the same layout/pages in a Maui hybrid app it also works fine without delay. The layout/pages are shared in a shared in a Razor Class Lib so they are 100% the same. 

## 💁 Possible Solution

I have no work around. I can share a movie/repo if needed but It should be fairly easy to reproduce. I wonder if others experiance the same delay.

## 🔦 Context

We want to build a new app/web application and share the ui using Fluent ui because we prefer it over Bootstrap. But this 8 seconds delay before the interactivity can be used is quite a roadblock in choosing Fluent over Bootstrap.

## 🌍 Your Environment

OS: Windows 11
VS: Version 17.9.5
Browser: Chrome Versie 123.0.6312.105 (Officiële build) (64-bits)
.Net 8.0.202
Microsoft.FluentUI.AspNetCore.Components 4.6.0

**Comment by vnbaaij** [comment]
Hi Michel,

Have you tried running the app in release mode? If not, can you test and let us know if you are still seeing the delay then?

I'm seeing a delay in debug mode, but think that has to de with the JavaScript debugger kicking in.

I did find a small errors in the templates because of this though, so thanks for flagging this. In the Client project the 8.0.0 packages were being used. Changed this to the latest version (8.0.3). Also, I believe there was a bug in the first packages wrt switching form Server to WASM mode, so that might have been contributing to what you were seeing as well.

**Comment by michelmoorlag** [comment]
Hi Vincent,

I upgraded the client project packages to version 8.03 and then I ran without debugging in release mode and wham the menu responded instantly. Now I know this is not an issue in release it is fine. Debugging takes some time to start but with hot reload it is not really an issue.

Thank you for the quick reponse and keep up the good work!
