### ISSUE TITLE
fix: DataGrid Resizable Columns not working if inside PullToRefresh

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#1865]
# 🐛 Bug Report
If, inside a pulltorefresh component, we add a Datagrid with resizable columns, this will not work as expected (it will resize the wrong column, etc)

## 💻 Repro or Code Sample

https://github.com/microsoft/fluentui-blazor/assets/36199751/c3b0787b-6b67-47a7-b97a-5ecf6cba570d

https://github.com/microsoft/fluentui-blazor/assets/36199751/8709c80a-c691-4926-96de-d9d5ba7b3c31

## 🤔 Expected Behavior
as the one without PullToRefresh

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] Any
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] Any
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1] NET 8, FluentUi 4.6.1

**Comment by vnbaaij** [comment]
I don't think this is a scenario we are going to support. PullToRefresh is meant for simple content structures like a listbox or set of divs. Not for something complex like the DataGrid. Besides, when used on the desktop, it uses an emulation for touch. I'm guessing that is where the issue is coming from
