### ISSUE TITLE
feat: add support for BackgroundColor & Color in FluentAnchor

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2100]
# 🙋 Feature Request

Since `FluentAnchor`s are basically `FluentButton` just as an `Href` I'm wondering why there is no support for `BackgroundColor` and `Color` just like there is for `FluentButton`

## 🤔 Expected Behavior

I would assume this two parameters are also available for FluentAnchors

**Comment by vnbaaij** [comment]
They are implemented with different web components. For buttons this is a much more used functionality. For anchor, you are the first to ask for this 😁. 
 
Adding specific parameters for this is a bit too much, I think. Especially because it enables breaking out of the Fluent Design more easily (which we don't want to promote). 

We do however already offer an example on how to achieve this on the demo site. See https://fluentui-blazor.net/Anchor#appearance
