### ISSUE TITLE
fix: FluentValidationMessage won't show message for an empty FluentTextArea component.

### ISSUE THREAD

**Issue by MertYacan** [microsoft/fluentui-blazor#2144]
# 🐛 Bug Report

FluentValidationMessage doesn't show an error message for a fluent text area with required field set true.

## 💻 Repro or Code Sample

```
@page "/test"

<EditForm Model="@dto" OnValidSubmit="HandleValidSubmit" FormName="batchForm">
    <DataAnnotationsValidator />
    <FluentValidationSummary />

    <FluentStack Orientation="Orientation.Vertical">
        <div>
            <FluentTextArea Rows=5 Cols=60 Name="description" @bind-Value="dto.Description" Label="Description" Required="true" />
            <FluentValidationMessage For="@(() => dto.Description)" />  @* This won't show message *@
        </div>
        <div>
            From:
            <FluentDatePicker @bind-Value="@(dto.From)" Required />
            <FluentTimePicker @bind-Value="@(dto.From)" />
            <br />
        </div>
        <div>
            To:
            <FluentDatePicker @bind-Value="@(dto.To)" Required />
            <FluentTimePicker @bind-Value="@(dto.To)" />
            <br />
        </div>

        <FluentCheckbox @bind-Value="@(dto.IsAdministrative)" Disabled="true" Label="Administrative Leave" />
        <FluentButton Type="ButtonType.Submit" Appearance="Appearance.Accent" Disabled="@(processing)">Submit</FluentButton>
    </FluentStack>
</EditForm>

@code {
    [SupplyParameterFromForm]
    private CreateBatchLeaveExcelDto dto { get; set; } = new()
        {
            From = new DateTime(DateOnly.FromDateTime(DateTime.Now), new TimeOnly(8, 0)),
            To = new DateTime(DateOnly.FromDateTime(DateTime.Now), new TimeOnly(17, 0))
        };

    private bool processing = false;

    public class CreateBatchLeaveExcelDto
    {
        public DateTime? From { get; set; }
        public DateTime? To { get; set; }
        public string? Description { get; set; }
        public bool IsAdministrative { get; set; }
    }

    private async Task HandleValidSubmit()

    {
        processing = true;
        await Task.Delay(500);
        processing = false;
    }
}
```
## 🤔 Expected Behavior

Works with FluentTextField
![image](https://github.com/microsoft/fluentui-blazor/assets/57174789/7a525074-7a0a-4c85-bdf8-a42803949b74)

## 😯 Current Behavior

Doesn't work with FluentTextArea
![image](https://github.com/microsoft/fluentui-blazor/assets/57174789/3a231b58-a490-4de2-ab7b-7e39148f7d0e)

## 🌍 Your Environment

* OS & Device: Windows on PC
* Browser: Google Chrome
* .NET and Fluent UI Blazor library Version 4.7.2

**Comment by vnbaaij** [comment]
Hi, 

Provided sample code is not ready-to-run. Please complement.

**Comment by MertYacan** [comment]
Hi, 

I am sorry. It should be ready-to-run now.

I realized when I run the app, and click submit it won't show the error message.

If i write something inside the description and clear the description again, then it will start to show the error message.

Thank you.

**Comment by vnbaaij** [comment]
It seems the standard HTML 5 validation checking and the `FluentTextArea` are not playing together nicely. I'll need to look into that further.

In the meantime I would advise you to not use the standard HTML validation but use Blazor's icw ours. Here is what you need to do:
1) add `@using System.ComponentModel.DataAnnotations` at the top of your page
2) add `novalidate` to your `EditForm` tag
3) change your `CreateBatchLeaveExcelDto` class to have:
```
 [Required(ErrorMessage = "Description is required")]
 public string? Description { get; set; }
```
Then clicking submit will show you an error immediately(*)
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/03e7ce7c-574e-460b-8510-f5a5a624b312)

Added benefit is that it will show the errors in the correct Fluent Design instead of the generic design 
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/9544af37-f5c7-44e2-993b-4bce3f6acead)
(which looks way worse if you ask ,e

(*) It will show the red border if below is in your CSS somewhere. I'm currently working on this and it will be automatically included in next release
```
fluent-text-area.invalid::part(control), 
fluent-text-field.invalid::part(root) {
    outline: calc(var(--stroke-width)* 1px) solid var(--error);
}
```

**PS**: Setting `Required="true" on a field does not automatically add any checks or logic. It's sole task (currently) is to display the required indicator (the red *)

**Comment by vnbaaij** [comment]
Closing this as a workaround is provided

**Comment by MertYacan** [comment]
Hi Vincent,

Thank you very much for the detailed explanation. It worked with your suggested changes.
