### ISSUE TITLE
fix: FluentSelect ValueChanged called with wrong option

### ISSUE THREAD

**Issue by ianclough** [microsoft/fluentui-blazor#2227]
# 🐛 Bug Report

I have a FluentSelect input with a small set of options, if the current value is not in the list options then it is added as the first option in order to display this value. Once another value is selected the this additional value is removed from the list of options.

The ValueChanged callback is invoked three times, twice with the correct selected value and then once with the next value in the options.

## 💻 Repro or Code Sample
```
@page "/"

@rendermode InteractiveServer

<h3>FluentDataGrid</h3>

<FluentSelect TOption="string"
              Label="Fluent select"
              Items="@Names"
              OptionValue="@(p => p)"
              OptionText="@(p => p)"
              Value="@_selectedValue"
              ValueChanged="ValueUpdated"
              @bind-SelectedOption="@_selectedValue" />


@code
{
    private string _selectedValue = "";
    private List<string> Names;

    private void ValueUpdated(string newValue)
    {
        Console.WriteLine("ValueUpdated: " + newValue);
        _selectedValue = newValue;
        Names = BuildOption();
    }

    protected override void OnParametersSet()
    {
        Console.WriteLine("OnParametersSet");
        Names = BuildOption();
    }

    private List<string> BuildOption()
    {
        List<string> options = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];
        if (!options.Contains(_selectedValue))
        {
            options.Insert(0, "");
        }

        return options;
    }
}
```
## 🤔 Expected Behavior

ValueChanged should be called, ideally only once, with the selected value.

## 😯 Current Behavior

The ValueChanged callback is invoked three times, twice with the correct selected value and then once with the next value in the options.

## 🌍 Your Environment

* OS & Device: Windows 10 in Parallels VM on a MacOS
* Browser: Microsoft Edge,
* .NET 8 and Fluent UI Blazor library 4.8.0

**Comment by vnbaaij** [comment]
Hi,

That the item is removed is quite logical. Initially `options` is empty and so is `_selectedValue`. The you select an item, say 'Wednesday'. Now `_selectedValue` gets set to that. Because of the code in `ValueUpdated`, you call `BuildOption` again, re-initialize the list and now `_selectedValue` (Wednesday) is actually in the list so it will not be added again.

With regards to the `ValueUpdated` being called multiple times, I think that is because of the change where the Select now inherits from `InputBase`. Will investigate further,
