### ISSUE TITLE
fix: MaximumSelectedOptions not limiting in FluentAutocomplete

### ISSUE THREAD

**Issue by hevilhuy** [microsoft/fluentui-blazor#2243]
# 🐛 Bug Report

MaximumSelectedOptions = 1 still allow the user to select more than 1 item

## 💻 Repro or Code Sample
```
<FluentAutocomplete Virtualize="true" TOption="UserSelectDisplay" Items="AvailableUsers" OptionText="x => x.Username" OptionValue="x => x.Id.ToString()" ValueText="@ctx.SelectedUserId" SelectedOptionsChanged="x=>Console.WriteLine(x.)" MaximumSelectedOptions="1" Context="user">
    <MaximumSelectedOptionsMessage>
        The maximum number of selected items has been reached.
    </MaximumSelectedOptionsMessage>
</FluentAutocomplete>
```
## 🤔 Expected Behavior

Should limit 1 selected item

## 😯 Current Behavior

Can select multiple items

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by vnbaaij** [comment]
Using the default example from the demo, setting the `MaximumSelectedOptions` to 1 and setting a `MaximumSelectedOptionsMessage` gives me this: 

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/745db41e-7739-49a3-9022-838bfba28683)

As you have not supplied ready to run reproduction code nor information about what version of the library you are using nor what kind of rendermode you are using, we must assume it is something in your code.

If you can supply the details and reproduction code, we can take a look. Otherwise I'll close this as not reproducible.

**Comment by hevilhuy** [comment]
It's Blazor WebAssembly Standalone.
I discorvered if I don't bind the `SelectedOptions` but only use `ValueText`, then this problem occurs. Kinda weird where I just need to select a single item but I need to declare a list.

**Comment by dvoituron** [comment]
In fact, there is no benefit in using this FluentAutocomplete component with the `Items` property. It is essential to use the `OnOptionsSearch` attribute to activate the search and return the list data to the user.

We'll change the documentation and disable this `Items` attribute in the case of this component.
I think it will be much clearer.

In your example, you therefore need to add a method like this one, which filters Items based on your criteria.

```csharp
private async Task OnSearchAsync(OptionsSearchEventArgs<Country> e)
{
    e.Items = AvailableUsers.Where(i => i.UserName.StartsWith(e.Text, StringComparison.OrdinalIgnoreCase))
                            .OrderBy(i => i.UserName);
}
```
