### ISSUE TITLE
fix: Duplicates IDs if Overflow in [Overflow]

### ISSUE THREAD

**Issue by f4n0** [microsoft/fluentui-blazor#2267]
# 🐛 Bug Report
I have a horizontal menu bar, within the Overflow component.
I've created a custom OverflowTemplate that will show the same buttons in a FluentPopOver. 

If the original button shows a popOver (Binded via Id), when it will become an Hidden Overflow Item, the id will be duplicated

## 💻 Repro or Code Sample
Code: https://github.com/f4n0/BlazorGenerator/blob/master/BlazorGenerator/Components/PageAction/ActionBar.razor
Result: https://f4n0.github.io/BlazorGenerator/card  - Just resize the page, and take a look to the "grouped" button

## 🤔 Expected Behavior
I think that it will be better to "strip" some attributes when an Item is hidden by overflow (for instance: Id). 

## 😯 Current Behavior
When overflow hits, I have duplicates ids in my code. 

When not hidden (take a close look to the find count, that is the Id):
![image](https://github.com/microsoft/fluentui-blazor/assets/36199751/e5c3c812-f211-4e0f-86cb-a721fd617093)

When Hidden (I have 2 ids that are the same, and with that, the popOver will break): 
![image](https://github.com/microsoft/fluentui-blazor/assets/36199751/6df21b5a-8cbf-4055-86cd-b74ec3906a40)
 

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] **Any**
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox] **Any**
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1] **Any**

**Comment by vnbaaij** [comment]
This is not just the `id` being duplicated. The whole element is duplicated and that is by design. The process is something like this:
- Render all elements
- After rendering run script that determines which elements don't fit
- Give these elements an `overflow` attribute, hide them from being displayed and put them in a collection
- When overflow is being shown, render the elements from the collection from previous step

There is no way that we can prevent the duplication of the id if the id is set manually (if it is not set, a new random one is being generated). If we would change the id in the copy phase, it still would not work as the popover (which is not under our span of control) is than not connected to that random id.

If you make your sample work by deleting the first element with the same id with the Dev Tools, it shows you another reason this construct of components is not desirable and won't work. The popover and the overflow both use the anchored region component at its base and all anchored regions get the same z-index: (9999). The popover gets partially shown behind the overflow:
![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/c646df31-fd6c-4951-b89d-0912423fc2cc)

I'm afraid that your use case of having a popover in an overflow is not going to work. We choose to not invest time in making this possible. If you ant to work on a PR with a solution, that is fine of course. We will gladly take that in.
