### ISSUE TITLE
fix: body background color variable 

### ISSUE THREAD

**Issue by mjacob2** [microsoft/fluentui-blazor#2271]
There is a slight discrepancy in background colors. This is related to the variable used in the css code. Both in light and dark mode.

There is:
![Zrzut ekranu 2024-06-26 115402](https://github.com/microsoft/fluentui-blazor/assets/26388420/34d2599e-73a9-4374-9368-837f0c378503)

There should be:
![Zrzut ekranu 2024-06-26 115719](https://github.com/microsoft/fluentui-blazor/assets/26388420/56857a0d-9cc6-41dc-b5a7-69bebeb00fc3)

The problem lies in this variable:
![Zrzut ekranu 2024-06-26 115918](https://github.com/microsoft/fluentui-blazor/assets/26388420/c9211598-79ae-4761-bd0b-113f6b4cb359)

To fix it it shoul be:
` background: var(--neutral-layer-1);`

**Comment by vnbaaij** [comment]
Hi,

Thanks for your report but this is actually 'by design'. 

For the template we choose to give the NavMenu that slightly different background. In the demo we show a situation how those can be made the same.

**Comment by mjacob2** [comment]
In what demo may I ask?
Could you please put informations like this up front?

**Comment by vnbaaij** [comment]
> In what demo may I ask? 
In the demo site (https://www.fluentui-blazor.net/). The one in your second screenshot. Code for that site is available here in the `examples` folder 

>Could you please put informations like this up front?
Not sure I understand what you mean by that. You want us to describe differences between the templates and demo environments?

**Comment by vnbaaij** [comment]
While I don't see some CSS changes in a demo environment as bugs in the library, I do agree that there should be consistency and that the demo should resemble what you get when creating a site from the templates. 

In `reboot.css` the background is set to `--neutral-fill-layer-rest` (#ffffff in light mode, #333333 in dark mde) so that is what we will use in the demo now as well. 

Change is pushed to dev (so can be seen on [preview](https://preview.fluentui-blazor.net/) site already. Will be on demo site with next release as well
