### ISSUE TITLE
Column Headers and Rows on FluentGrid Control Lose Style with Horizontal Scroll

### ISSUE THREAD

**Issue by jmjcoelho** [microsoft/fluentui-blazor#2281]
[FluentGridColumnHeaderIssue.zip](https://github.com/user-attachments/files/16012665/FluentGridColumnHeaderIssue.zip)
**Title**: 

**Description**:
When using the FluentGrid control, the column headers and rows lose their style when there is a horizontal scroll. This issue specifically occurs with column that are initially hidden and then shown as you scroll horizontally. The styling of these headers breaks, resulting in a poor visual presentation.

**Steps to Reproduce**:
1. Download the attached  project with a FluentGrid control that shows the issue.
2. Run the project.
3. Scroll horizontally to the right until initially hidden column headers become visible.
4. Observe the styling of these column headers as they appear.

**Expected Behavior**:
The column headers and rows, including those initially hidden and then shown upon scrolling, should maintain their style, ensuring a consistent visual presentation.

**Actual Behavior**:
The column headers and rows  that were initially hidden and then shown upon scrolling lose their style, making the headers visually inconsistent.

**Additional Context**:
This issue occurs in both Chrome and Edge browsers. 

**Environment**:
- Operating System: Windows 11
- Browser: Latest Google Chrome and Edge
- FluentUI : 4.8.1

**Comment by vnbaaij** [comment]
Hi, 

Thanks for your report. We will look into it shortly!

**Comment by vnbaaij** [comment]
This is unfortunately an problem in the current version of the underlying web components in combination with the `GenerateHeaderOption.Sticky` option. As a (sort of) solution, you can set the header type to not be sticky as there won't be a background set on the header cells.

I recreated a similar table on [the FAST Explorer](https://explore.fast.design/components/fast-data-grid) site and the same is happening there (the table is wider and I scrolled to the right):

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/c05aa235-232d-40ba-a860-7c3367a1ebd6)

As the web components team is busy it building their next version and deprecation of older libs is taking place, I'm afraid there won't be a fix for this soon (if ever).

I'm closing this issue because it can't be fixed on our side. I you want, you can open an issue in the FAST repo for this, but as said I think changes of seeing it solved are slim.

PS. If you want to have a horizontal scrolling grid, do it like shown at https://www.fluentui-blazor.net/DataGrid#tablewithscrollbars. Much smoother then setting an overflow on the grid itself.

```
<div style="display: table; table-layout: fixed; width: 100%;">
    <div style="overflow-x: auto;">
        <FluentDataGrid Id="weathergrid"...>
        :
        : 
        </FluentDataGrid>
    </div>
</div>
```

**Comment by jmjcoelho** [comment]
Hi,
  
I found that adding **Style="min-width: max-content;"** to the FluentDataGrid , as shown in the example you previously mentioned, ensures that the column headers and rows render properly.

Regards
Jose Coelho

**Comment by vnbaaij** [comment]
That is a great find @jmjcoelho! Glad that got you unblocked.

I'll make sure to add a note on this to the docs.
