### ISSUE TITLE
feat: add Label location control to FluentTextArea

### ISSUE THREAD

**Issue by PascalVorwerk** [microsoft/fluentui-blazor#2450]
# 🙋 Feature Request

Right now, if you wrap the FluentTextArea inside a FluentStack with vertical orientation it makes the label also transfer to the stack orientation. My request would be to either make it a choice to have the label in front of the text area or on top, and then make sure it doesn't move around because of any wrapping components.

## 🤔 Expected Behavior

FluentTextArea with no label in as a parameter but a separate label provided above it (my current workaround:
![image](https://github.com/user-attachments/assets/53c8a002-358c-4110-b19d-f378dcae4bbe)
![image](https://github.com/user-attachments/assets/4578efe9-bb80-4990-8c94-a0bd0302f55d)

## 😯 Current Behavior

FluentTextArea with a label and FluentStack around it:
![image](https://github.com/user-attachments/assets/7651aff8-055d-43fa-9775-87b837caf4fb)
![image](https://github.com/user-attachments/assets/6aff96e1-1fc4-4aa6-9034-1f15172667ec)

## 💁 Possible Solution
I'm not sure if the same thing happens when u wrap a FluentText inside a fluent stack with vertical orientation. If so, i would suggest to always keep the label on top as suggested in the documentation, or make it able to select through a parameter to have it be in front or on top. By default the label would be on top

Something like:
```
<FluentTextArea Label="Body" LabelLocation="LabelLocation.Front" />
```

**Comment by vnbaaij** [comment]
Hi,

You just need to surround the TextArea with a div or a span so that the rendered html will be seen as one block by the stack.
Example:
```
<FluentStack VerticalAlignment="VerticalAlignment.Center">
    <span>
        <FluentTextArea Label="Parameters" @bind-Value="@Description" Cols="130" Rows="5" Maxlength="350" ReadOnly Required />
    </span>
    <FluentButton >Copy to clipboard</FluentButton>
</FluentStack>

@code {
    private string Description { get; set; } = "This is a test";
}
```

gives you:
![image](https://github.com/user-attachments/assets/66d91f51-9473-4f1e-a266-d280670cf85f)


p.s. Next time please include actual code instead of an image of code. Makes it easier to copy for us. (Use three ` to start and end a code block here in the Markdown)

**Comment by vnbaaij** [comment]
We can definitely still discuss! I just closed this as it is not actionable from our side. Please let me explain why. If you think a different solution/approach is doable then happy to hear and learn.

The Stack component is in the end nothing more (when rendered) than a div with some styles applied. In case of a horizontal stack it gets `display: flex; flex-direction: row;`. When vertical the flex-direction will be column. 

It will apply that imposed layout (style) on any html child element it encounters, In the case of an TextArea (or TextField) with a label, two html elements will get created; a label and a <fluent-text...> web component. 

There is no way (that I know off) to have these two to be seen as 1 besides putting them in another container. We can't change the way the web components renders and we can't assume a label is always present so we don't by default render a container ourselves as a precaution.

Looking at the next version of the web components, I see an improvement here. The image shows what gets rendered for a fluent-text-input component:
![image](https://github.com/user-attachments/assets/7cea99e0-53af-4b4e-b77e-4b93ab5f4a65)

As you can see the label is then part of the input so it would not be influenced by the container like it is now.

**Comment by PascalVorwerk** [comment]
Right, i understand better now. If the choice was made to not wrap the component inside another wrapper i can see why. Maybe this is a point that could be added to the documentation? I was just suprised it happened the first time, as you dont expect it to happen from just a Parameter. I understand that the current workaround is more desirable then wrapping

**Comment by joriverm** [comment]
@vnbaaij : i was looking around because we noticed some issues having things like a textbox inside our own flex container, and saw this issue/your last comment. i can understand your comment, and have told the developers to put a div around our FluentTextField to make the label not have its own spot in the flex container.

However, you mention web-components' new version has a built in label (nice!) and that would solve the issue. got any idea when that would release? ive been waiting for more than 2 months for them to release 3.0.0 because of multiple bug fixes..

**Comment by vnbaaij** [comment]
> However, you mention web-components' new version has a built in label (nice!) and that would solve the issue. got any idea when that would release? ive been waiting for more than 2 months for them to release 3.0.0 because of multiple bug fixes..

Oh, that will definitely take another couple of months. On our side it will be a major new version (v5) and we will be changing a lot of things. We will take our time to do it right.
We do not know yet how 'complete' the initial release of the v3 web components will be. Our v5 will most probably not have feature parity with v4 initially. And because of all the changes in the web components, we will have a lot of breaking changes on our side. We are working on thorough migration docs.

**Comment by joriverm** [comment]
no problem, thanks! im looking forward to it all and will keep an eye open for it :)

**Comment by dvoituron** [comment]
> no problem, thanks! im looking forward to it all and will keep an eye open for it :)

You will find a first Draft documentation of these changes on this page.
https://github.com/microsoft/fluentui-blazor/blob/dev-v5/examples/Demo/FluentUI.Demo.Client/Documentation/GetStarted/Version5.md
