### ISSUE TITLE
fix: Header not correctly aligned with RTL direction in FluentAccordionItem

### ISSUE THREAD

**Issue by aminmashayekhi** [microsoft/fluentui-blazor#2484]
# 🐛 Bug Report

When page direction is RightToLeft, Heading of FluentAccordionItem does not align correctly.

## 🤔 Expected Behavior
The "text-align" of button class most be "start":
![image](https://github.com/user-attachments/assets/cc38d671-e93e-4218-9d73-49e7087cdf67)

## 😯 Current Behavior
but currently it is "left"!

![image](https://github.com/user-attachments/assets/7669653f-e87c-45e1-a789-7afde414e8ce)

## 💁 Possible Solution
in FleuntUI web-components package's accordion-item, it is "start", but in fluentui-blazor it is "left" so i think its value should change to default.

![image](https://github.com/user-attachments/assets/949ae5ca-c8d3-41b3-b0e8-0b25b271faad)

**Comment by dvoituron** [comment]
As you said, this problem comes from the [Web Component](https://github.com/microsoft/fluentui/tree/web-components-v2/packages/web-components/src) project. We have no control over this code. Can you add a problem to this repository?
But they're in the process of migrating to version 3, and I'm not sure they'll do the update in this v2.

In the meantime, you can work around the problem in your project by adding this code.
```css
fluent-accordion-item::part(button) {
    text-align: start;
}
```
