### ISSUE TITLE
fix: The UI is only displayed correctly on iOS 16 when refreshed

### ISSUE THREAD

**Issue by Jakan** [microsoft/fluentui-blazor#2666]
# 🐛 Bug Report

I created a new Blazor Web App (Interactive Server) using the template.

When I go to this page using Safari with iOS 16, it is displayed completely white and without any style. Only when I click on update does it display correctly.
This problem occurs every time a page is changed

## 💻 Repro or Code Sample

The Template

## 🤔 Expected Behavior

The display should also be displayed correctly the first time it is called up

## 😯 Current Behavior

see summary
**First call:**
<img width="336" alt="Screen1" src="https://github.com/user-attachments/assets/9c243f48-7fcc-4a97-bfd6-85084abafdcc">

**After i click refresh on this site:**
<img width="325" alt="Screen2" src="https://github.com/user-attachments/assets/033f10af-37d6-4210-8472-cc7b5b397076">

**I switch to weather-page:**
<img width="321" alt="Screen3" src="https://github.com/user-attachments/assets/30c705d1-3d9f-4166-9de5-ea827e8e05cc">

and so on...

* OS & Device: [iPhone
* Browser Apple Safari
* .NET and Fluent UI Blazor library current Version

**Comment by dvoituron** [comment]
Hi,
I'm using iOS 17.6.1 and I don't have this issue.

Looking at your screens it seems to be a style download problem. But without more information and without iPhone/iOS16 hardware we can't help you any further :-(

**Comment by Jakan** [comment]
Hi,

Version 16 can be simulated for free on this page. The behavior there is exactly the same as on my device with iOS 16 (White without styling and on refresh it styles the app correct).

[https://appetize.io/demo?device=iphone14pro&osVersion=16.2&record=true]

Greetings

**Comment by vnbaaij** [comment]
Hi,

We can indeed simulate iOS 16 there but we can't research anything about what might be happening. If I choose iOS 17 in that same emulator (for the same model)m the side loads fine. 

We do not have time to invest researching what is causing this. Especially since iOS 17 is available and working. 
I'm closing this one. If there is any specifics on why we would need to support iOS 16, please let us know. In general though we only support latest version of browsers (which in this case is coupled, right)
