### ISSUE TITLE
Horizontal scrollbar is placed at bottom of content instead of bottom of viewport.

### ISSUE THREAD

**Issue by JohnVottero** [microsoft/fluentui-blazor#2743]
# 🐛 Bug Report

In a FluentDialog which contains FluentTabs, if the content of a tab page is large, scroll bars are
added but the horizontal scroll bar is placed at the bottom of the content instead of the bottom of the
tab panel.

## 💻 Repro or Code Sample

This repository reproduces this issue:

https://github.com/JohnVottero/ScrollBarInTabPage

## 🤔 Expected Behavior

When scroll bars are added they should be added to the tab panel so that they are always
visible. You should not have to scroll to bring a scroll bar into view.

## 😯 Current Behavior

The vertical scroll bar is correct but, the horizontal scroll bar is at the bottom of the content.

## 💁 Possible Solution

I don't know of one.

## 🔦 Context

Having to scroll down to get to the horizontal scroll bar makes it hard to work because the
content that you want to scroll horizontally may scroll out of view when you scroll vertically
to get to the horizontal scroll bar.

## 🌍 Your Environment

Windows 11, .NET 8, FluentUI-Blazor 4.10.1, Edge browser

**Comment by vnbaaij** [comment]
You can solve this one by applying a `Style` on the `FluentTab`:

```
<FluentTab Label="Scroll" Style="display:flex;">
```

I'll investigate if it makes sense to have this added by default.

**Comment by vnbaaij** [comment]
We have a gazillion `FluentTabs` in the demo, but none of them is using the `Height` parameter. I've done a test with setting a default height on the demo sections:
![image](https://github.com/user-attachments/assets/28e2b073-26fb-45e2-a35c-2fb5a6c1ea99)

Conclusion: setting a `display: flex;` on the tab panel does not go well. 

This is kind of expected. Tabs can be used in many different containers and because of that can have very different requirements with regards to when/how scrollbars should be shown. We will not be making a change to the default settings we have now, as those setting seem to work well in most cases and, more importantly, we expose ways to make them work good in the cases where the defaults are not working well.
