### ISSUE TITLE
TreeView selection (continuation of issue #2797)

### ISSUE THREAD

**Issue by vnbaaij** [microsoft/fluentui-blazor#2810]
> Then another bug appears when you want to react to selection changed events.
> There are 3 different selection changed events on `FluentTreeView` - `CurrentSelectedChanged`, `OnSelectedChange` and `SelectedItemChanged`.
> Only the latter two apply, but both have bugs of their own.
> 
> **OnSelectedChanged**:
> Event fired **after** the selection already on next target.
> ```
> <FluentTreeView Items="@list" @bind-SelectedItem="@this.selectedItem" OnSelectedChange="this.selectedChanged" />
> <label>@this.testtext</label>
> 
> @code
> {
>     private string testtext = String.Empty;
>     private ITreeViewItem? selectedItem;
>     private List<TreeViewItem> list = new List<TreeViewItem>() { new TreeViewItem() { Text = "test 1" }, new TreeViewItem() { Text = "test 2" }, new TreeViewItem() { Text = "test 3" } };
> 
>     private void selectedChanged(FluentTreeItem? args)
>     {
>         if (args != null && args.Selected) this.testtext = args.Text!;
>     }
> }
> ```
> 
> Yields:
> ![Image](https://github.com/user-attachments/assets/9b139ef0-44a1-402a-adb7-b95616100e97)
> 
> **SelectedItemChanged**:
> This forces us to set up `SelectedItem` as a one-way bind only - could be managed if not for the following bug:
> Doesn't clear the previous selection and doesn't fire the SelectedItemChanged event when adding items (nothing shown in Visual Studio debugger log. Does get triggered when you manually click on items.)
> 
> ```
> <FluentTreeView Items="@list" SelectedItem="@this.selectedItem" SelectedItemChanged="@this.SelectedItemChanged" />
> 
> <FluentButton Appearance="Appearance.Accent" OnClick="this.buttonClick">Add</FluentButton>
> 
> @code
> {
>     private int counter = 0;
>     private ITreeViewItem? selectedItem;
>     private List<TreeViewItem> list = new List<TreeViewItem>() { new TreeViewItem() { Text = "test 1" }, new TreeViewItem() { Text = "test 2" } };
> 
>     private void buttonClick(MouseEventArgs e)
>     {
>         // this.selectedItem = null; // does not help
>         var newitem = new TreeViewItem() { Text = "broken " + (counter++).ToString() };
>         this.list.Add(newitem);
>         this.selectedItem = newitem;
>     }
> 
>     private void SelectedItemChanged(ITreeViewItem? args)
>     {
>         if (args != null) System.Diagnostics.Trace.WriteLine(args!.Text); // not fired during add new item
>     }
> }
> ```
> 
> Yields:
> ![Image](https://github.com/user-attachments/assets/1c913c62-bd3b-40e0-a67c-a54924cd562c) 

 _Originally posted by @markoweb2 in [#2797](https://github.com/microsoft/fluentui-blazor/issues/2797#issuecomment-2408950492)_

**Comment by vnbaaij** [comment]
For tracking the selected item, you just need this:

```
<FluentTreeView Items="@list" @bind-SelectedItem="@this.selectedItem"  />
<label>Test text: @this.testtext</label><br />
<label>Selected item: @selectedItem?.Text</label>

@code
{
    private string testtext = String.Empty;
    private ITreeViewItem? selectedItem;

    private List<TreeViewItem> list = new List<TreeViewItem>() { new TreeViewItem() { Text = "test 1" }, new TreeViewItem() { Text = "test 2" }, new TreeViewItem() { Text = "test 3" } };

    private void selectedChanged(FluentTreeItem? args)
    {
        if (args != null && args.Selected) this.testtext = args.Text!;
    }
}
```
**OnSelectChanged** is **not** called after the event but it is actually called **twice**. Once for the new and once for the old item. The unfortunate thing is the web component sends them in the wrong order! And we can't change
that

For the **SelectedItemChanged** part, you can again just use the `@bind-SelectedItem` like this:

```
<FluentTreeView Items="@list" @bind-SelectedItem="@this.selectedItem"  />

<FluentButton Appearance="Appearance.Accent" OnClick="this.buttonClick">Add</FluentButton>

<label>@selectedItem?.Text</label>

@code
{
    private int counter = 0;
    private ITreeViewItem? selectedItem;
    private List<TreeViewItem> list = new List<TreeViewItem>() { new TreeViewItem() { Text = "test 1" }, new TreeViewItem() { Text = "test 2" } };

    private void buttonClick(MouseEventArgs e)
    {
        // this.selectedItem = null; // does not help
        var newitem = new TreeViewItem() { Text = "broken " + (counter++).ToString() };
        this.list.Add(newitem);
        this.selectedItem = newitem;
    }


}
```
That does not fix the broken add thing, but I already discussed that before.

@markoweb2 Please review and let us know any additional questions.

**Comment by markoweb2** [comment]
Both examples you now gave have removed the event handler completely and reverted to binding only.
This does not cover my usage scenario.

I need to react to the event, ie user clicked in the TreeView and changed the selection.
During this event handler, I need to get the new selected item and show other information related to it or navigate to another page passing the Id as a URL parameter etc. A binding does not do that, I can't react to it with further code.

With the **OnSelectChanged** method I just wanted to prove that the selection lags behind during the event:
```
    private void selectedChanged(FluentTreeItem? args)
    {
        if (args != null && args.Selected) this.testtext = args.Text!;
    }
```

The intention was not to assign the value to a label, akin to a binding, just used it for visual illustration.
I went over the code with the debugger again, the problem is not that the underlying component sends the event two times in the wrong order, the problem is that `args.Selected` value is **reversed**.

For exampel, I have test1 selected, I click on test2.
First the event is triggered for test1, it is supposed to be unselected, but `args.Selected == true`.
Then the event is triggered for test2, it is supposed to be selected ,but `args.Selected == false`.

If you can't fix the true/false value from within the component, can you perhaps rename the event argument parameter `Selected` to `Deslected`, so as to match the correct boolen value?

For the **SelectedItemChanged** part, the idea is to add a new item via code to the TreeView, set it in code to visually selected and also trigger the selection changed event handler.
This is conjuction with handling the scenario, when the user clicks on the TreeView to change the selection. Both scenarios must work, but I can only use one event handler.

When adding a pre-selected item to the TreeView, I could call the event handler manually from code and not rely on the TreeView component to call out the event handler, but first I need to get a working event handler for when the user changes the selection from UI.

`SelectedItem + SelectedItemChanged` => this combination I understand is completely broken from within the underlying component and not fixable.
`@bind-SelectedItem + OnSelectedChange` => this combination should work, if the args.Selected parameter would get fixed somehow.

**Comment by vnbaaij** [comment]
On my phone now, so can't go into the code in detail. Just thinking if  @bind-SelectedItem:after could help here

**Comment by vnbaaij** [comment]
Ok, going through the code, I've found a bug in the `HandleSelectedChangeAsync` method in the `FluentTreeItem.razor.cs` file. The item's `Selected` value was not being set there before calling `ItemSelectedChangeAsync` on the `FluentTreeView` parent (withe the tree item as it's parameter). This code is only called if `Items` is not null. `ItemSelectedChangeAsync` invokes `OnSelectedChange` 

So if selected was not being set on that item, OnSelectedChange would get called with the old value, hence the reversed behavior. After making this change, I've confirmed (with the test code) that the correct `Selected` value is being used in your `selectedChange` method.
