### ISSUE TITLE
fix: Scrollbars appear when opening FluentPopover near screen edge

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#2904]
# 🐛 Bug Report

See:

![Image](https://github.com/user-attachments/assets/8831276f-0843-43fe-b2a3-ce88779b9af4)

Seems kind of similar to https://github.com/microsoft/fluentui-blazor/issues/2736

## 💻 Repro or Code Sample

Code here: https://github.com/dotnet/aspire/pull/6607

The problem appeared when the button that the popover is anchored to moved near to the edge of the page.

## 🤔 Expected Behavior

No scroll bars added because popover content is inside browser window

## 😯 Current Behavior

Scroll bars added.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by dvoituron** [comment]
I think the best solution is to hide the scrollbar in the `body` tag, because your main container will then display the scrollbar.
But you can also add the `FixedPlacement="true"` attribute to convert the CSS `position: absolute;` to `position: fixed;`.

```css
body, .body {
    overflow: hidden;
}
```

## Before

![Image](https://github.com/user-attachments/assets/0b21ca79-bff3-4cf4-8226-aba0ea939bc5)

## After

![Image](https://github.com/user-attachments/assets/42a37ebb-f609-4844-98aa-113851605f2d)
