### ISSUE TITLE
Hello! Will web-components 3.0 be supported?

### ISSUE THREAD

**Issue by bit365** [microsoft/fluentui-blazor#2955]
Hello, seeing that web-components 3.0 has been released, will fluentui blazor support version 3.0? If I am developing an application based on the current FluentUI Blazor now, whether it supports smooth upgrade to the new version in the future, thank you.

**Comment by vnbaaij** [comment]
Hi,

The Fluent UI Web Components v3 have **not** been released yet. They are currently in beta.

We have started the work on using v3 in our dev-v5 branch. It will be a major new release with a lot of (breaking) charges due to the changes being made in the Web Components. 
Also, the initial final release of the Web Components will not offer all components that are available in v2 today. 


We will do our best to provide upgrade documentation etc. But a drop-in replacement upgrade will not be possible.

**Comment by bit365** [comment]
Thank you very much for your contribution and effort, thank you very much.
