### ISSUE TITLE
fix: Embedding FluentSwitch in FluentRadio

### ISSUE THREAD

**Issue by gemelo-Peer** [microsoft/fluentui-blazor#3006]
# 🐛 Bug Report

When a FluentSwitch is embedded in the content of a FluentRadio, a type of "interference" occurs. On the one hand, the radio point can be deactivated by clicking on the switch and, on the other hand, the radios start to flicker and activate alternately when the switches are pressed.
 
![alt text](https://files.gemelo.de/temp/FluentRadioProblem.gif)

## 💻 Repro or Code Sample

```html
<FluentRadioGroup Value="@("Test1")" Orientation="Orientation.Vertical">
    <FluentRadio Value="@("Test1")">
        This is the first option
        <FluentSwitch Name="Test1" Value="true">Test 1</FluentSwitch>
    </FluentRadio>
    <FluentRadio Value="@("Test2")">
        This is the second option
        <FluentSwitch Name="Test2" Value="true">Test 2</FluentSwitch>
    </FluentRadio>
</FluentRadioGroup>
```

## 🤔 Expected Behavior

I'm not sure if it's not allowed to embed other controls inside a radio, but normally radios and switches should behave correctly.

## 😯 Current Behavior

See above

## 🌍 Your Environment

.NET and AspNetCore 9.0.0
Microsoft.FluentUI.AspNetCore.Components 4.10.4

**Comment by gemelo-Peer** [comment]
I was able to isolate the problem in such a way that this problem only occurs from version 4.10.1 onwards. With version 4.10.0 or lower, everything works as expected.

**Comment by dvoituron** [comment]
The problem was also present in previous versions: the `FluentRadioGroup.Value` attribute is updated to `on` when the user clicks on the Switch. But in the latest version, the value binding updates this value, in loop, between `on` and `Test2`.

I haven't found a solution yet.
I will continue to find out why the `FluentRadioGroup` is updated to `on`.

**Comment by dvoituron** [comment]
I think the problem comes from Web Components because when I use this code, when I modify a Switch, the `fluent-radio-group` changes to `value=“on”`. And I haven't found a way to interfere with this.

I don't think we'll be able to fix this in version 4. But I'm going to check how it works in v5 (which uses the new Web Components).

```html
<fluent-radio-group orientation="vertical">
    <fluent-radio>
        This is the first option
        <fluent-switch>Test1</fluent-switch>
    </fluent-radio>
    <fluent-radio>
        This is the second option
        <fluent-switch>Test2</fluent-switch>
    </fluent-radio>
</fluent-radio-group>
```
https://github.com/user-attachments/assets/bf22be44-d889-4452-bae0-8f4235d67df2

**Comment by dvoituron** [comment]
After checking, the next version won't be able to handle this case either: in fact, it won't even be possible to display a **FluentSwitch** component in a **FluentRadio**.
I think the reason is that it's not advisable to have several interactive components in a **FluentGroup**. The next WebComponents have added an `slot=“input”` attribute to be applied to items: only one per **FluentRadio** element.

**Comment by gemelo-Peer** [comment]
In my opinion, the fact that switching the FluentSwitch also switches the FluentRadio entry is acceptable or even preferable in my specific case.
The bigger problem from my point of view is the flickering between the states, which occurs in the current version but not in the previous version. Have you been able to find out anything about this?

**Comment by dvoituron** [comment]
> The bigger problem from my point of view is the flickering between the states, which occurs in the current version but not in the previous version. Have you been able to find out anything about this?

Yes, the problem is that the **FluentSwitch** sets the **FluentRadioGroup.Value** to `on`.
At the same time, the **FluentRadio** sets the same **FluentRadioGroup.Value** to `Test1` (the Radio value).
The result is an infinite loop in these changes.

The previous version didn't handle the binding on the **FluentRadioGroup** correctly, and the end result was sometimes inconsistent.
By correcting this, we end up with a ‘correct’ update, but one that loops in this case.

I can't see any way of solving this particular problem. Except by not adding a **FluentSwitch** to a **FluentRadio** 😉
