### ISSUE TITLE
feat: add Ability for line breaks in MessageBox  text

### ISSUE THREAD

**Issue by TristanColeNovus** [microsoft/fluentui-blazor#3009]
# 🙋 Feature Request

When using a MessageBox dialog via the DialogService.
It would be really useful to have a method of adding a new line break to the message text.

## 🤔 Expected Behavior
Using a line line:
`var dialog = await dialogService.ShowConfirmationAsync("Are you sure you want to delete this item? \n This will also remove any linked items.", "Yes", "No", "Delete Item");`

The output box would show the 2 lines with a break:
```
Are you sure you want to delete this item?
This will also remove any linked items.
```

## 😯 Current Behavior

Currently there is no rendering of a line break, so the text just flows.
```
Are you sure you want to delete this item? This will also remove any linked items.
```

## 💁 Possible Solution

Render the standard `Environment.NewLine` character or some alterative (`\n`) to html `<br />`,

**Comment by vnbaaij** [comment]
Hi,

You can already do this, but 
1) You need to use the standard HTML `<br />` for that (bonus: you can also use other markup  like `<strong>`, etc). 
2) You need to call `DialogService.ShowMessageBoxAsync` instead of `DialogService.ShowConfirmationAsync`. 

An example of this is provided in the demo site at https://www.fluentui-blazor.net/MessageBox#messageboxasync and then the 'Custom message'-part. This is a bit more cumbersome but at least you can use it today. 

For the next version we will make a change to always convert the message to a `MarkupString` so then you only need to do 1) from then on:

![Image](https://github.com/user-attachments/assets/cc27b37f-81c7-4709-a148-99c1a96be19c)

p.s we are not going to do automatic translation from `\n` to`<br />` etc because that will probably lead to never ending asks of new automatic translations. We assume developers using this library have enough understanding of HTML to use this.
