### ISSUE TITLE
Selectable components rtl issue

### ISSUE THREAD

**Issue by ehsangfl** [microsoft/fluentui-blazor#386]
all selectable components like listview, select, treeview ... have rtl issue
but Treeview does not show any bullet 

![Untitled](https://user-images.githubusercontent.com/10611397/236666042-c69d7f19-6142-4bbf-adca-5682afbcd99f.jpg)

version : 2.2.2
dotnet : 8

**Comment by vnbaaij** [comment]
I'm working on the TreeView issue. For the Select/Listbox/Combobox, this is an issue in the underlying Web Components. I raised an issue in the FAST repo to track that (https://github.com/microsoft/fast/issues/6727)

**Comment by vnbaaij** [comment]
`FluentTreeView`/RTL is fixed in the demo environment. There is no change to the `FluentTreeView` component itself needed. 2 things need to be done to make this work correctly:

1. You need to use and call the `Direction` design token. See `SwitchDirection()` in `DemoMainLayout.razor.cs`)
2. You need to set the style on the container the components are in through JS interop. Could be `<body>` tag or any other `<div>`. In case of the demo site the is a `<div>` with an id="container". See `switchDirection()` in `DemoMainLayout.razor.js`
