### ISSUE TITLE
Fluent ui fully native blazor?

### ISSUE THREAD

**Issue by danielpastoor** [microsoft/fluentui-blazor#458]
Fluent ui blazor is still a wrapper for web-components.

Are the future plans to make fluent ui blazor fully native?

**Comment by dvoituron** [comment]
Hello.

Yes, we include web components to respect the common FluentUI visual for the different frameworks. 

But we decided to create components more adapted to Blazor (even if we don't use only web components) in order to provide a maximum of components for devs. 

We're currently working on this in the web-components branch.
