### ISSUE TITLE
fix: Screen flashes when in dark mode and site is first opened.

### ISSUE THREAD

**Issue by mrpmorris** [microsoft/fluentui-blazor#471]
1: Set dark mode on your computer
2: Open the demo site
3: Site opens in light mode
4: Site flicks to dark mode
5: Seek a specialist in eye burns

**Comment by vnbaaij** [comment]
I can do ` window.matchMedia("(prefers-color-scheme: dark)").matches ;` in JavaScript not sooner then in `OnAfterRender` and then it is already too late...
Any other suggestions on how to prevent this flash?
![giphy](https://github.com/microsoft/fluentui-blazor/assets/1761079/0574a979-476f-4d17-aecd-8f43c721f7a8)

**Comment by mrpmorris** [comment]
Shouldn't the FAST css handle it before Blazor even starts up?

**Comment by BieleckiLtd** [comment]
> [...] Any other suggestions on how to prevent this flash?

Dark by default and later switch to light if required?

**Comment by andreisaperski** [comment]
There're two parts:
 - when Fluent UI WC lib is loaded, it creates 'base-layer-luminance' token with default value [`StandardLuminance.LightMode` (0.98)](https://github.com/microsoft/fluentui/blob/3f805b9bca38c866d56233f1b89868465b9d3bb0/packages/web-components/src/design-tokens.ts#L180), respective variable is assigned to 'html' node.
 - in case of Server hosting model, there's a period of time when page is displayed, but site.css is not applied yet - page is effectively in Light mode during this time.

Fluent UI WC doesn't provide a mechanism to override default value for 'base-layer-luminance'. Something like `window['DefaultBaseLayerLuminance'] || StandardLuminance.LightMode` instead of `StandardLuminance.LightMode`, probably, wouldn't hurt. Such fix could be applied to web-components-v2.XXX.min.js, but it's not very practical - it needs to be re-applied to new versions.
The second part could be mitigated with some bootstrap styles placed in host file (_Layout.cshtml) e.g.

```html
...
    <base href="~/" />
    <style>
        :root {
            --neutral-base-color: #212121;
            --neutral-fill-layer-rest: #ffffff;
        }
        @@media(prefers-color-scheme: dark) {
            :root {
                --neutral-base-color: #ffffff;
                --neutral-fill-layer-rest: #464646;
            }
        }

        body,
        #container {
            color: var(--neutral-base-color);
            background-color: var(--neutral-fill-layer-rest);
        }
    </style>
    <link href="_content/FluentUI.Demo.Shared/css/site.css" rel="stylesheet" />
...
```

Made sort of [PoC](https://github.com/andreisaperski/fluentui-blazor/tree/fix-471-global-var-default-style) with altered web-components-v2.5.16.min.js and bootstrap style 


https://github.com/microsoft/fluentui-blazor/assets/30940385/4bbafbe0-8712-4f28-ac1d-9936fd61bbbb

**Comment by vnbaaij** [comment]
@andreisaperski love this! Will see how we can integrate this.

**Comment by vnbaaij** [comment]
We have a solution  implemented for it in the demo site. Please use the source as a reference on solving this. See also https://github.com/microsoft/fluentui-blazor/issues/706#issuecomment-1785158671
