### ISSUE TITLE
EditForm not get value from FluentTextField  when submit by Enter key.

### ISSUE THREAD

**Issue by nhanttnhantt** [microsoft/fluentui-blazor#672]
## 😯 Current Behavior

Im using EditForm with FluentTextField
when submit form by Enter key, value binding can not get from FluentTextField.
but submit by button, value binding can get from FluentTextField.
im test with InputText, it alway get value when submit by Enter key or button.

How can i take value when submit by Enter key with FluentTextField.

**Comment by joecuevasjr** [comment]
I experienced this as well, as a workaround I ended up setting a handler method for the FluentTextField's `@onkeyup` callback. Within the method, I check for the "Enter" key and if so I proceed to call the same Submit method that EditForm calls. 

However, this workaround is inadequate if you're relying on the EditForm to do validation on submit, since it skips it in the simplest form of implementation.

**Comment by vnbaaij** [comment]
Another workaround is to use a `FluentButton` where `Type=ButtonType.Button` instead of submit. This way enter will not trigger a submit.

The behavior comes from the underlying web components. We are looking if/how we can change that behavior

**Comment by joecuevasjr** [comment]
> Another workaround is to use a `FluentButton` where `Type=ButtonType.Button` instead of submit. This way enter will not trigger a submit.
> 
> The behavior comes from the underlying web components. We are looking if/how we can change that behavior

With this solution, pressing enter wont trigger a submit but the `FluentButton` also loses the capability to submit the form via click. This could be fixed by handling the `OnClick` event with a method to call JavaScript and submit the form. There's probably a better way to approach this vis the `EditForm` itself though.
