### ISSUE TITLE
feat: FluentTextField autocomplete should be a string or enum and not a boolean

### ISSUE THREAD

**Issue by RonPeters** [microsoft/fluentui-blazor#680]
Autocomplete for text inputs is not just on or off. There are numerous strings you can assign to specify the type of information the field represents so the browser can autocomplete intelligently: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

FluentTextField only allows a boolean `AutoComplete=bool?`

If I try to set an HTML standard such as `autocomplete="name"`, I get an invalid cast error. I also cannot workaround by setting the AdditionalAttributes dictionary directly.

This is a clear deficiency in the API. I don't have a good proposal besides turning the property into a string? which may have backward compatibility issues. But this needs to be addressed.

Also, in the current implementation, setting autocomplete="false" doesn't render anything. It should render autocomplete="off" explicitly so that the browser knows not to guess at the autocomplete based on the ID or name of the input. Also, why do all the inputs render id="control"? Isn't that improper HTML (sharing ID values across multiple elements)?

Anyway, I feel like there is a lot to be addressed here.

**Comment by dvoituron** [comment]
We use the FluentUI WebComponents library to render our Blazor components. We've added this property, which doesn't yet exist in these WebComponents.

You're right, Autocomplete should be a String, and we'll look into the possibility of changing it.

You can currently get around this limitation by adding JavaScript code to update this Input.

All inputs have an ´id=control´ because they are isolated in web components. https://developer.mozilla.org/en-US/docs/Web/API/Web_components


You can use the Id attribute to identify your components

**Comment by dvoituron** [comment]
Example of JavaScript code. 

´´´javascript
export function setAutocomplete(id, value) {
    const fieldElement = document.querySelector("#" + id)?.shadowRoot?.querySelector("#control");

    if (!!fieldElement) {
        fieldElement?.setAttribute("autocomplete", value);
    }
}
´´´

**Comment by dvoituron** [comment]
Will be fixed in the next release: #682
