### ISSUE TITLE
fix: Error in VS with FluentIcon Color tag

### ISSUE THREAD

**Issue by AndyEdmonds** [microsoft/fluentui-blazor#681]
```
<FluentIcon Icon="@Icons.Regular.Size24.BrainCircuit" Color="Color.Lightweight" />
```
Generates an error: 
Error (active)	CS7003	Unexpected use of an unbound generic name
on the "Color" tag.		
This is upgrading from V2 to V3 in Visual Studio 17.6.6

**Comment by dvoituron** [comment]
You should set the Icon property without @ symbol. 

The new **FluentIcon** component has 2 attributes for displaying a specific icon:

- **Icon** is a **Type** representing the icon class that will be instantiated by the component.
- **Value** is an **Icon object** that will be used by the component.

**Comment by dvoituron** [comment]
Are you sure that is on the Color attribute ? And not on the Icon attribute ?

Try to remove the @ set in the Icon attribute, specifying the **Type** of icon. 

Because, the new **FluentIcon** component has 2 attributes for displaying a specific icon:

- **Icon** is a **Type** representing the icon class that will be instantiated by the component.
- **Value** is an **Icon object** that will be used by the component.

**Comment by AndyEdmonds** [comment]
Hi,

Thanks for that. 
Your examples have the "@" in them. For instance:
```
<div style="display:flex">
    <FluentButton Appearance="Appearance.Neutral"><FluentIcon Slot="start" Icon="@Icons.Regular.Size20.ArrowCircleLeft" /> Button with icon in 'start' slot</FluentButton>
    <FluentButton Appearance="Appearance.Neutral"><FluentIcon Slot="end" Icon="@Icons.Regular.Size20.ArrowCircleRight" /> Button with icon in 'end' slot</FluentButton>
</div>
```
in https://www.fluentui-blazor.net/Icon

Getting rid of the "@" seems to fix the error.

**Comment by dvoituron** [comment]
Ho, Sorry about this typo in the documentation, to be corrected quickly.

**Comment by vnbaaij** [comment]
Closing this. Example is updated for next release. No further action required.
