### ISSUE TITLE
fix: scrolling of parent component is NOT disabled in FluentDialog

### ISSUE THREAD

**Issue by trubby22** [microsoft/fluentui-blazor#750]
# 🐛 Bug Report

When using the FluentDialog component, scrolling in the parent component is not disabled.

## 💻 Repro or Code Sample

This behaviour can be seen in the [official example](https://www.fluentui-blazor.net/Dialog#dialogwithoutusingdi).

## 🤔 Expected Behavior

The enclosing component should have scrolling disabled as long as the FluentDialog is open.

## 😯 Current Behavior

The enclosing component is scrollable (even when the cursor is inside the FluentDialog and the FluenDialog is focused).

## 💁 Possible Solution

Copy the behaviour present in a [similar library](https://www.blazorfluentui.net/DialogPage).

## 🔦 Context

I have a FluentDialog with lots of vertical content - it has a vertical scroll bar. When scrolling inside FluentDialog, the parent component also scrolls, which is a bad user experience.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser: Google Chrome Version 116.0.5845.188 (Official Build) (64-bit)
* .NET: net6.0;net7.0
* Microsoft.Fast.Components.FluentUI: 3.0.1

**Comment by vnbaaij** [comment]
This will be fixed in v3.1. See https://black-pebble-0dc79cb03-758.westeurope.3.azurestaticapps.net/Dialog and Panel, Splash screen and Messagebox pages for how it is implemented. Basically scrolling is now always prevented/disabled (pure CSS, no Javascript needed) but it can be influenced through `DialogParameters` or with `FluentDialog` parameter
