### ISSUE TITLE
fix: FluentSelect Multiple is always expanded

### ISSUE THREAD

**Issue by mattgoedde** [microsoft/fluentui-blazor#792]
# 🐛 Bug Report

When multiple is true, the FluentSelect dropdown is always expanded. This appears to also be the case in the documentation website.

## 💻 Repro or Code Sample

```csharp
<FluentSelect TOption="Person"
              Items="@Data.People"
              Id="people-listbox2"
              Multiple="true"
              OptionValue="@(p => p.PersonId.ToString())"
              OptionText="@(p => p.LastName + ", " + p.FirstName)"
              @bind-Value="@SelectedValue"
              @bind-SelectedOptions="@SelectedOptions" />
```

## 🤔 Expected Behavior

The dropdown should start closed (open=false) and be open-able and close-able.

## 😯 Current Behavior

The dropdown is stuck open.
![image](https://github.com/microsoft/fluentui-blazor/assets/61606506/81507809-1f18-4c97-a15d-031092bcc861)

**Comment by vnbaaij** [comment]
This has always been like that. See for example https://calm-sea-053fa6a03-archivesv2.westeurope.3.azurestaticapps.net/Select#multiple-items

You can also go to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select and add multiple to the first sample. It will then also show a listbox.

**Comment by TuckermanRav** [comment]
"This has always been like that" - All that tells me it's been wrong, and has always been wrong.  I've never seen a multi-select drop down that doesn't collapse after the user makes their selections.  In fact, I'm trying to wrap my head around the logic in even defending the notion.  There are zero Microsoft products that behave this way.  Not Logic Apps, not Azure Data Studio, not power BI not Azure Portal.

**Comment by vnbaaij** [comment]
I'm hopeful we will get a solution for this with the v3 web components. Until then there is nothing we can do about how the v2 web components are handling his. 

Please understand we are completely separate from the React Fluent UI team and are doing this as a side project. Our time and resources are (very) limited. 

V2 web components are now in 'archive state' so we will not see any fixes coming to that version anymore as the team is focusing on v3.

> "This has always been like that" - All that tells me it's been wrong, and has always been wrong. I've never seen a multi-select drop down that doesn't collapse after the user makes their selections. In fact, I'm trying to wrap my head around the logic in even defending the notion. There are zero Microsoft products that behave this way. Not Logic Apps, not Azure Data Studio, not power BI not Azure Portal.

@TuckermanRav (and others who have raised a thumbs up) we work with what we get from the web components for these Blazor components. The issue lies in the source and we simply **can't** change that (and **do not** have the resources to do so). Not defending anything, just stating the facts.

**Comment by lasbrojen** [comment]
Missing this feature right now :)

**Comment by S1lvan07** [comment]
@vnbaaij Is this still beeing worked on, or is it planned to be completed in the future? 

Thanks for the response.

**Comment by vnbaaij** [comment]
Yes, we are still working on that for v5. 

In fact, new select component has just been merged in. See https://fluentui-blazor-v5.azurewebsites.net/

**Comment by ZANZAAA** [comment]
Any update on this? I cannot see the MultiSelect with dropdown for the v5: https://fluentui-blazor-v5.azurewebsites.net/Forms

**Comment by vnbaaij** [comment]
@ZANZAAA see https://v5.fluentui-blazor.net/Lists/Select and then the Multiple example

**Comment by ZANZAAA** [comment]
Omg, I'm blind, sorry. Thanks @vnbaaij
