### ISSUE TITLE
fix: NavMenu changing to base route by itself

### ISSUE THREAD

**Issue by Narvalex** [microsoft/fluentui-blazor#800]
# 🐛 Bug Report

This issue might be related to #789 fix. It seems that I can not go to child routes of a sub page whenever I have the `<Navigating>` component of the `<Router>` parent component. This does not happen when the base route is `/` in the `FluentNavMenu` component. Be aware that I'm using the latest FluentUI package that contains the fix for #789 .

## 💻 Repro or Code Sample

1. Clone [this repo](https://github.com/Narvalex/FluentUIBlazorTests)
2. Go to the `/sub-page` route
3. Try to go to a child route, like Counter page or Fetch Data page.
![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/e912568b-53d7-4088-a5b1-1b1fd6eb3db9)

## 🤔 Expected Behavior

You should be able to go to `/sub-page/counter` and `/sub-page/fetchdata` and stay in that location.

## 😯 Current Behavior

The app redirects you to the `/sub-page` route after a few miliseconds.

## 💁 Possible Solution

If you remove the `<Navigating>` component from the `<Router>` the automatic redirection will not happen. 

## 🔦 Context

I'm trying to use the `FluentNavMenu` component without getting rid of the `Navigating` component.

## 🌍 Your Environment

.NET 7 and Fluent UI 3.1.1

**Comment by vnbaaij** [comment]
Ok, I think I have all bases covered now...🥵
@Narvalex  can you test with the attached (unsigned) package (remove the `.zip` extension)?
[Microsoft.Fast.Components.FluentUI.3.1.2-preview.1.23271.6.nupkg.zip](https://github.com/microsoft/fluentui-blazor/files/12751505/Microsoft.Fast.Components.FluentUI.3.1.2-preview.1.23271.6.nupkg.zip)

**Comment by Narvalex** [comment]
Hey @vnbaaij , thanks for your hard work! Unfortunately I found a new bug with your fix. You are not able to change route with the menu item that have the `/sub-page` route from the Nav Menu. The `<a>` tag that is in the header works well, but not from the `FluentMenuNav`.
You can reproduce the error in [the repo that I shared](https://github.com/Narvalex/FluentUIBlazorTests) that includes the pre-release nuget that you build.

![image](https://github.com/microsoft/fluentui-blazor/assets/11648387/2cf5a9c5-8986-4ac2-9806-06e98cc11be7)

**Comment by vnbaaij** [comment]
I think we have a situation here were we need to choose which route scheme we will support and which not.
Right now I have it working with a situation where **route parameters** exist for a certain page:
```
@page "/Panel"
@page "/Panel/{*panelroute}"
:
:
@code {
    [Parameter]
    public string? PanelRoute { get; set; }
}
``` 
Navigating to `/Panel`, `/Panel/123` or `/Panel/123/456` all works. Navigation item `/Panel` is selected in `FluentNavMenu` and url shows correct value.

In your repo situation `/sub-page`, `/sub-page/counter` and `/sub-page/fetchdata` are all **real** pages.

As far as I know, there is **no** way to distinguish between these two situations. 

I think I'm inclined to make the situation with the route parameters working and let 'your' situation fail as it does now. Reason is because your situation is much easier to circumvent (as you are in control of the @page attribute). For example, changing  the `LoadSubPage` code in your repo to like below makes it all work. In we support your situation, one could never work with route attributes.

Thoughts?

```
 public static void LoadSubPageMenu()
 {
        MainLayout.menu = new List<MenuItem>
        {
            new MenuItem
            {
                Icon = new Icons.Regular.Size24.Home(),
                Text = "SubPage",
                Href = "/sub-page"
            },
            new MenuItem
            {
                Icon = new Icons.Regular.Size24.NumberCircle1(),
                Text = "Counter",
                Href = "/counter"
            },
            new MenuItem
            {
                Icon = new Icons.Regular.Size24.CalendarAgenda(),
                Text = "Fetch Data",
                Href = "/fetchdata"
            }
        };
    }
```

**Comment by Narvalex** [comment]
I understand. If we clearly document this known issue in the Demo App, I’m fine with that. It would be nice to handle both situations, but this workaround is not bad either.
