### ISSUE TITLE
feat: add Enum support to/in FluentSelect

### ISSUE THREAD

**Issue by yongkeecho** [microsoft/fluentui-blazor#817]
# 🙋 Feature Request

It seems @bind-Value/Value in FluentSelect is always 'string' type while TOption is set as an enum type. Therefore there is no way to bind an enum value selection to an object without converting from string to enum type.

## 🤔 Expected Behavior

`
<FluentTextField @bind-Value="@Content.TextValue">Text Value:</FluentTextField>
<FluentNumberField @bind-Value="@Content.NumericValue">Numeric Value:</FluentNumberField >
<FluentSelect TOption="MyEnum" Items="@Enum.GetValues(typeof(MyEnum)).Cast<MyEnum>()" @bind-Value="@Content.EnumValue" />

@code {
enum MyEnum
{
   EnumValue1, EnumValue2
}

class MyClass 
{
  string TextValue;
  int NumericValue;
  MyEnum EnumValue
}

public MyClass Content;

}
`

## 🔦 Context

Along with the Dialog, the enum support will make it smoother to bind all the values of an object from DialogResult without conversion.

**Comment by StevenRasmussen** [comment]
While the above does "work"... I feel that it's lacking a little:
* No flexibility regarding the display text
* No option to select an 'Empty' value

When working with enums it would be nice to simply specify an enum type and bind the value but provide flexibility for the above.

I have created my own implementation of a `FluentEnumSelect` component that wraps the `FluentSelect`.  I am happy to work on a PR if @dvoituron  or @vnbaaij feel that it has merits and potential to be accepted into the project. Thoughts?

**Comment by dvoituron** [comment]
It would be more interesting to see if it's possible to adapt current components to support **Enums**.
But I don't think that adding new components depending on the type of data (Enum, etc.) is very appropriate at the moment.

**Comment by StevenRasmussen** [comment]
Hmmm... I think that at least in the case of the `FluentSelect` there might be a way to adapt it to work well with enums at least for purposes of allowing some customization around the display text.  It might even be able to determine if the bound value is nullable or not to provide the option of allowing an empty value as well.  I'll see if I can't get a draft PR put together and submitted for review.

**Comment by StevenRasmussen** [comment]
I looked into this over the weekend and it looks like it's not really feasible with the current architecture and the constraints around the `TOption`.  Although we could add a `TEnum` or "special type" as you mentioned above that feels like a bit of a hack to me.  Ideally I feel like there should be a refactor that uses an internal collection for holding the values that ultimately get rendered instead of using the supplied `Items` collection.  In this manner the `TOption` could still be an `enum` but internally the enum would be wrapped into an `Option<TEnum>` and stored in the internal collection.  What would the chances be that you would accept a PR with this type of re-architecture?
