### ISSUE TITLE
fix: FluentCard injecting too many css parameters in parent container

### ISSUE THREAD

**Issue by zharchimage** [microsoft/fluentui-blazor#818]
# 🐛 Bug Report

Hi! First of all thanks for the amazing library which I'm really enjoying using. I have noticed that when using the `FluentCard` it injects more than thirty unecessary CSS parameters in the parent container, in this case a `<div>`  which is uneficient to send as many parameters over a Blazor Circuit.

## 💻 Repro or Code Sample

Paste this code in the `/counter` page of the default Blazor project template:

`
    <div id="parentDiv">
        <FluentCard>
            <h2>Hello World!</h2>
            <FluentButton Appearance="@Appearance.Accent">Click Me</FluentButton>
        </FluentCard>
    </div>
`

## 🤔 Expected Behavior

`<div id="parentDiv">` not to have any CSS as I didn't specify any.

## 😯 Current Behavior

All those properties are being injected to the parent container, and it gets worse if `FluentCard` is being used in `lists`

![image](https://github.com/microsoft/fluentui-blazor/assets/3091146/7ca4262b-f53b-4096-8e5e-0c5ffb9689a2)

I have tested removing the `FluentCard` and the extra CSS doesn't appear anymore.

**Comment by dvoituron** [comment]
It's by design, we are using the `fluent-card` web component. 

The `fluent-card` component is a visual container and design system provider. By default `fluent-card` applies `neutralFillCard` to its background that is calculated from its parent design system provider. If a custom background color is desired the attribute `card-background-color` is available, this will reset the cards design system to that value. Cards are snapshots of content that are typically used in a group to present collections of related information.

See https://learn.microsoft.com/en-us/fluent-ui/web-components/components/card

**Comment by zharchimage** [comment]
Thanks for the answer @dvoituron I don't get it very well how could I remove all those styles from the parent then, tried to add `card-background-color` but it is not available, tried to set the style to `null` but doesn't reset the styles. Should I surround every `FluentCard` with a null style provider or something? Thanks!

**Comment by dvoituron** [comment]
Why do you want to remove these styles? If you want to have other styles in the Card, you can use a <div> with only a shadow style.

**Comment by zharchimage** [comment]
I'm using the `FluentCard` as a template for a `ListView` I created so when I'm specting the DOM It is full of redundant CSS that I don't need in the `FluentCard` parent making things harder to debug, but probably will end up reimplementing the layout to mimic the `FluentCard` if it is not possible to override the styles.

**Comment by zharchimage** [comment]
I have implemented finally `SlimFluentCard` thanks for the explanation and the answer!
