### ISSUE TITLE
fix: AutoComplete dropdown is anchored in wrong place

### ISSUE THREAD

**Issue by ra-one** [microsoft/fluentui-blazor#820]
# 🐛 Bug Report

AutoComplete component drop-down opens up, instead of down, the options available are not displayed

## 💻 Repro or Code Sample

[FluentServerMRE.zip](https://github.com/microsoft/fluentui-blazor/files/12802339/FluentServerMRE.zip)

## 🤔 Expected Behavior
The drop down should open/anchored to bottom.
![image](https://github.com/microsoft/fluentui-blazor/assets/2285281/e2fd556f-9831-4e1d-adc0-44272e00a66b)

## 😯 Current Behavior
The drop down opens anchored to top.
![image](https://github.com/microsoft/fluentui-blazor/assets/2285281/32dfed05-c40e-4466-a0dc-5cac8ae8bc0c)

## 💁 Possible Solution

Not sure but it seems if i remove/comment out `<h1>Hello, world! - with bug</h1>` (comment line 7 in `index.razor` in sample code)  it works as expected.
Also instead of removing header element if i add empty div after `AutoComplete` (uncomment line 36 in `index.razor` in sample code) it works as expected.

## 🌍 Your Environment

* OS & Device: Win 11
* Browser: Tested with Microsoft Edge/Firefox/Chrome/Brave
* .NET:  8.0.100-rc.1.23455.8
* Microsoft.Fast.Components.FluentUI: 3.1.1
* Visual Studio: Community 2022 (64-bit) - 17.8.0 Preview 2.0

**Comment by dvoituron** [comment]
Thanks. Let me check.

**Comment by dvoituron** [comment]
This is because the height of `body` is too small and the drop-down list doesn't have enough space to display the panel.

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/bfbb52e6-e58d-43a2-90bd-cadd256a5d6a)

You can fix that setting `height: 100vh` for the `container` class (for example).

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/10995aca-74bc-4bc9-b09c-bd768e83f6a4)

@vnbaaij We should update the **FluentUI Template** to include a Full Width/Height.
