### ISSUE TITLE
fix: `FluentOverflow` in combination with `FluentToolbar` does not add items to overflow

### ISSUE THREAD

**Issue by hksalessio** [microsoft/fluentui-blazor#873]
# 🐛 Bug Report

If a `FluentOverflow` is used inside a `FluentToolbar` and the website is resized too fast, for exmaple by resizing the browser window, `FluentOverflow` does not detect the resize and the items do not get added to the overflow. In our case we end up with the following:

<img width="287" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/143792830/a3bc8c5a-88f3-48f6-81f6-f122edbfe212">

It does work, however, if the website is resized slowly.

There could be problems with how I have written the code/styles. In that case, feel free to correct/help me.

## 💻 Repro or Code Sample

The following code leads to the wrapping as seen in the above picture:

`Toolbar.razor`
```
<FluentToolbar Style="width: 100%;">
	<span slot="start" style="width: 100%">
		<FluentOverflow>
			<MoreButtonTemplate>
				<FluentButton Appearance="Appearance.Lightweight">
					<FluentIcon Icon="Icons.Regular.Size16.MoreVertical" />
				</FluentButton>
			</MoreButtonTemplate>

			<OverflowTemplate>
				<FluentTooltip Anchor="@context.IdMoreButton" UseTooltipService="false">
					@foreach (var item in context.ItemsOverflow)
					{
						<FluentMenuItem>
							Button
						</FluentMenuItem>
					}
				</FluentTooltip>
			</OverflowTemplate>

			<ChildContent>
				<FluentOverflowItem><FluentButton>Button</FluentButton></FluentOverflowItem>

				<FluentOverflowItem><FluentButton>Button</FluentButton></FluentOverflowItem>

				<FluentOverflowItem><FluentButton>Button</FluentButton></FluentOverflowItem>
			</ChildContent>
		</FluentOverflow>
	</span>

	<span slot="end">
		<FluentSearch />
	</span>
</FluentToolbar>
```

`Toolbar.razor.css`
```
::deep fluent-toolbar::part(start) {
    flex-grow: 1;
}
```

**Comment by vnbaaij** [comment]
Hi,

I'm afraid your example code is wrong. The `FluentOverflow` is a sort of 'container' component that needs to wrap what you want to overflow. 
Try to rework the code so that your toolbar is inside the `ChildContent` of the overflow component.  Take a look at https://github.com/microsoft/fluentui-blazor/blob/dev/examples/Demo/Shared/Pages/Overflow/Examples/OverflowHorizontalExample.razor for how we do it in the demo site. 
I'm not completely sure though if the toolbar component can be used in this way.
