### ISSUE TITLE
fix: Virtualized DataGrid sets align-items: center; and no property to change. 

### ISSUE THREAD

**Issue by Ogglas** [microsoft/fluentui-blazor#944]
# 🐛 Bug Report

Adding `Virtualize="true"` for `FluentDataGrid` sets `fluent-data-grid-row` with style `align-items: center;`.  Since everything else is set to `Align.Start` as default this looks a bit weird. In 2x this was not set. 

https://calm-sea-053fa6a03-archivesv3.westeurope.3.azurestaticapps.net/DataGrid#virtualizedgrid

## 💁 Possible Solution

A possible solution would be to add `Align` to `FluentDataGrid` as well. As a workaround I have used `<FluentDataGrid RowStyle="@(rS => "align-items: start;")"` 

## 🌍 Your Environment

* .NET and FAST Version: .NET 7 and Microsoft.Fast.Components.FluentUI Version 3.3.0

**Comment by vnbaaij** [comment]
This was added because with `Virtualize` you have the option to set the ItemSize (this is not specific for the grid but more for virtualize itself), If thisItemSize is et and we don't do `align-items: center`, things do not line up nicely anymore. 

Here is an image taken from the demo site where the ItemSize for the second grid has been set to a bigger value on purpose. For the first grid you can see the text and the buttons do not line up when not centered

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/b88118bc-8442-45eb-b819-17f271c4c1c8)

I think both look weird when not using center.

If anything would change, then I would rather say that we always use center (regardless of ItemSize set. Thoughts?

**Comment by vnbaaij** [comment]
@Ogglas any comment?

**Comment by Ogglas** [comment]
@vnbaaij Sorry, missed this. I think a property called `Align` to `FluentDataGrid` would be best. In that case the user can decide how the grid should align.

**Comment by vnbaaij** [comment]
There is already the `RowStyle` property so let's re-use that. Setting it to something like
```
RowStyle="@(x => x.Item1 == x.Item1 ?  "align-items: top" : null)"
``` 
 (it needs to be func and it is late and can't come up with anything better) will work with the next version as I built in a check on the row to not put it `align-items: center` when a style is being used.
