### ISSUE TITLE
fix: [FluentMenu] in [Microsoft.FluentUI.AspNetCore.Components@4.0.0]

### ISSUE THREAD

**Issue by sdpfigueiredo** [microsoft/fluentui-blazor#963]
# 🐛 Bug Report

FluentMenu no longer adds an overlay to close the menu automatically when Anchor is not provided.
using `OpenAsync` opens the Menu with no way to close it other than clicking an option

## 🤔 Expected Behavior
The Menu should close when the user clicks outside the menu boundaries

**Comment by vnbaaij** [comment]
Hi,

This behavior is not tied to an Anchor being present but to a menu being Amchored (draw the menu below the component clicked (true) or using the mouse coordinates (false)) and needs to be there. Otherwise, if you have a component like this:

```
<FluentMenu Open="true" Anchored="false">
```
It will be displayed on rendering of a page with an overlay shown This makes the rest of the page unusable till either clicked or a menu choice had been made

**Comment by sdpfigueiredo** [comment]
Sorry @vnbaaij but I still don't think this is the desired behavior, if you check the "Simple context menu" here: https://www.fluentui-blazor.net/Menu if you open the context menu it doesn't close when you click away, is this by design?

**Comment by DanielCordell** [comment]
I'm inclined to agree with @sdpfigueiredo  , I've just noticed this as well and find it odd that in order to close a menu by clicking externally I _have_ to click on a menu item, or I'm always forced to create a `FluentOverlay` when this should be the default behaviour.
