### ISSUE TITLE
fix: Bind parameter values not updating FluentSelect component

### ISSUE THREAD

**Issue by msantor** [microsoft/fluentui-blazor#983]
# 🐛 Bug Report

There seems to be a problem updating FluentSelect values using the `@bind-SelectedOption` or `@bind-Value` parameters. The components do not consistently reflect the value assigned to the variable used in the binding.

## 💻 Repro or Code Sample

```
@page "/fluent-select-test"
@using Microsoft.FluentUI.AspNetCore.Components

<div>
	<h3>Using @@bind-SelectedOption</h3>
	<p>SelectedOption: @selectedOption?.GetHashCode()</p>
	<p>SelectedOption Text: @selectedOption?.Text</p>
	<p>SelectedOption Value: @selectedOption?.Value</p>

	<FluentLabel>Select 1</FluentLabel>
	<FluentSelect AriaLabel="Select 1"
				Items="items"
				TOption="Option<int?>"
				OptionText="@(o => o.Text?.ToString() ?? "")"
				OptionValue="@(o => o.Value?.ToString() ?? "")"
				@bind-SelectedOption="selectedOption" />
	<FluentLabel>Select 2</FluentLabel>
	<FluentSelect AriaLabel="Select 2"
				Items="items"
				TOption="Option<int?>"
				OptionText="@(o => o.Text?.ToString() ?? "")"
				OptionValue="@(o => o.Value?.ToString() ?? "")"
				@bind-SelectedOption="selectedOption" />
</div>
<br />
<FluentButton OnClick="@(args => selectedOption = items.Single(i => i.Value == null))">Set Option null</FluentButton>
<FluentButton OnClick="@(args => selectedOption = items.Single(i => i.Value == 1))">Set Option 1</FluentButton>
<FluentButton OnClick="@(args => selectedOption = items.Single(i => i.Value == 2))">Set Option 2</FluentButton>
<FluentButton OnClick="@(args => selectedOption = items.Single(i => i.Value == 3))">Set Option 3</FluentButton>
<br />
<br />
<div>
	<h3>Using @@bind-Value</h3>
	<p>SelectedValue: @selectedValue</p>
	<FluentLabel>Select 3</FluentLabel>
	<FluentSelect AriaLabel="Select 3"
				Items="items"
				TOption="Option<int?>"
				OptionText="@(o => o.Text?.ToString() ?? "")"
				OptionValue="@(o => o.Value?.ToString() ?? "")"
				@bind-Value="selectedValue" />
	<FluentLabel>Select 4</FluentLabel>
	<FluentSelect AriaLabel="Select 4"
				Items="items"
				TOption="Option<int?>"
				OptionText="@(o => o.Text?.ToString() ?? "")"
				OptionValue="@(o => o.Value?.ToString() ?? "")"
				@bind-Value="selectedValue" />
</div>
<br />
<FluentButton OnClick="@(args => selectedValue = items.Single(i => i.Value == null).Value.ToString())">Set Option null</FluentButton>
<FluentButton OnClick="@(args => selectedValue = items.Single(i => i.Value == 1).Value.ToString())">Set Option 1</FluentButton>
<FluentButton OnClick="@(args => selectedValue = items.Single(i => i.Value == 2).Value.ToString())">Set Option 2</FluentButton>
<FluentButton OnClick="@(args => selectedValue = items.Single(i => i.Value == 3).Value.ToString())">Set Option 3</FluentButton>

@code {
	Option<int?>? selectedOption;
	string? selectedValue;
	List<Option<int?>> items = new List<Option<int?>>
	{
		new() { Text = null, Value = null },
		new() { Text = 1, Value = 1 },
		new() { Text = 2, Value = 2 },
		new() { Text = 3, Value = 3 }
	};
}
```

## 🤔 Expected Behavior

The component values for Select 1 and Select 2 should stay in sync when the corresponding component changes
and
The component values for Select 3 and Select 4 should stay in sync when the corresponding component changes.

## 😯 Current Behavior

Using the `@bind-SelectedOption` parameter the components get out of sync when trying to select a value that has already been selected at least once. Using Select 1 select values 1-3 in order, the Select 2 component values change to match what is selected in Select 1. However, when you select another value using the Select 1 component from this point Select 2 never changes.

Using the `@bind-Value` parameter the components are less prone to getting out of sync. If only one of the components is used to change the value the other component will stay in sync. However, if changes are made to both components eventually I was able to get them out of sync.

## 💁 Possible Solution

I'm not aware of a solution but I did step through the code in ListComponentBase and observed that the render tree is being built correctly. I'm guessing there could be some race condition with the event handling.

## 🔦 Context

I'm using the FluentSelect to allow users to select from a set of values and use their selection to filter data in a FluentDataGrid. I want to be able to allow the user to click a "Clear" option which reverts the FluentSelect to the starting value resulting in the starting data set to be re-displayed.

## 🌍 Your Environment

Observed behavior with both Blazor Server and Blazor WebAssembly projects using version 4.0.0 of the Blazor Fluent UI library and .NET 8. I haven't tried prior versions of the library or .NET.

* OS & Device: Windows on PC
* Browser: Microsoft Edge, Mozilla FireFox
* .NET and FAST Version: .NET 8, Blazor Fluent UI 4.0.0

**Comment by for7raid** [comment]
the same issue on FAST 3.3.0

**Comment by pk9r327** [comment]
The code for `ListComponentBase<TOption>` was missing some handlers.
### For `@bind-SelectedOption`
Even though `SelectedOption` is set, `Value` is not changed (it always defaults to `null`). Because `Value` does not change, the `current-value` of `fluent-select` will not be updated from this source code (see line 16).
https://github.com/microsoft/fluentui-blazor/blob/25a2c0c85352c5da1b5ab7c34de18b916999bef3/src/Core/Components/List/FluentSelect.razor#L7-L19
I see code that updates `Value` using `SelectedOption` via `InternalValue` but the conditions for this to happen are probably not for this case.
```C#
protected override void OnParametersSet()
{
    ...
```
https://github.com/microsoft/fluentui-blazor/blob/25a2c0c85352c5da1b5ab7c34de18b916999bef3/src/Core/Components/List/ListComponentBase.cs#L256-L260
```C#
    ...
}
 ```

You may want to see more about the definition of `InternalValue` here.
https://github.com/microsoft/fluentui-blazor/blob/25a2c0c85352c5da1b5ab7c34de18b916999bef3/src/Core/Components/List/ListComponentBase.cs#L27-L49

Perhaps @fluentui/web-components' script automatically assigns a value to the `current-value` of `fluent-select` based on the first `selected` of all `fluent-option`. However, it can only do this the first time for each `fluent-option` (see picture, or you can test it at https://codepen.io/pk9r327/pen/ExrqxYK)
![image](https://github.com/microsoft/fluentui-blazor/assets/72692627/0d89437b-4986-46db-b5a4-e4206cee90cc)

### For `@bind-Value`

Is similar to `@bind-SelectedOption`, even though `Value` is set, `SelectedOption` is not changed (but it can be updated by `OnChangedHandlerAsync`). Since `SelectedOption` is not for display, everything looks fine, but `SelectedOption` does not match `Value` causing a condition in `OnSelectedItemChangedHandlerAsync` to become abnormal.
https://github.com/microsoft/fluentui-blazor/blob/25a2c0c85352c5da1b5ab7c34de18b916999bef3/src/Core/Components/List/ListComponentBase.cs#L380-L384

### Summarize

The solution here is to make `SelectedOption` and `Value` match each other in case `SelectedOption` changes and in case `Value` changes.

I fixed it in local, but I didn't take care of `Multiple` when fixing this, which may cause errors when using `Multiple`. I also changed quite a bit of code in `ListComponentBase.cs` while debugging so I need time to review it. Please wait for a PR.

Below is a video I shot to show this issue, dark mode is the result after I fixed it.

https://github.com/microsoft/fluentui-blazor/assets/72692627/ece46ec2-6561-4fc7-865f-efd5241f8941

**Comment by vnbaaij** [comment]
@pk9r327 Looking forward to that PR!
